version: '3.8'

services:
  django:
    build:
      context: ./VectorHRS
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    depends_on:
      mysql_database:
        condition: service_healthy  # Ensure the service is healthy before starting Django
    environment:
      - DJANGO_SETTINGS_MODULE=VectorHRS.settings
    command: >
      sh -c "python manage.py migrate && 
             python create_superuser.py &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./VectorHRS:/VectorHRS

  mysql_database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'your_database_name'
      MYSQL_USER: 'your_database_user'
      MYSQL_PASSWORD: 'your_database_password'
      MYSQL_ROOT_PASSWORD: 'your_root_password'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u your_database_user -pyour_database_password"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
