import { operations } from "../schemas";
import { AxiosResponse } from "axios";
export declare const cms_api_main_listing_view: (headers: any, _apiPrefix?: string) => Promise<AxiosResponse<operations["cms_api_main_listing_view"]["responses"][200]["schema"]>>;
export declare const cms_api_main_documents_find_view: (headers: any, _apiPrefix?: string) => Promise<AxiosResponse<operations["cms_api_main_documents_find_view"]["responses"][200]["schema"]>>;
export declare const cms_api_main_detail_view: (id: string, headers: any, _apiPrefix?: string) => Promise<AxiosResponse<operations["cms_api_main_detail_view"]["responses"][200]["schema"]>>;
export declare const cms_api_main_listing_view: (headers: any, _apiPrefix?: string) => Promise<AxiosResponse<operations["cms_api_main_listing_view"]["responses"][200]["schema"]>>;
export declare const cms_api_main_images_find_view: (headers: any, _apiPrefix?: string) => Promise<AxiosResponse<operations["cms_api_main_images_find_view"]["responses"][200]["schema"]>>;
export declare const cms_api_main_detail_view: (id: string, headers: any, _apiPrefix?: string) => Promise<AxiosResponse<operations["cms_api_main_detail_view"]["responses"][200]["schema"]>>;
export declare const cms_api_main_listing_view: (headers: any, _apiPrefix?: string) => Promise<AxiosResponse<operations["cms_api_main_listing_view"]["responses"][200]["schema"]>>;
export declare const cms_api_main_pages_find_view: (headers: any, _apiPrefix?: string) => Promise<AxiosResponse<operations["cms_api_main_pages_find_view"]["responses"][200]["schema"]>>;
export declare const cms_api_main_detail_view: (id: string, headers: any, _apiPrefix?: string) => Promise<AxiosResponse<operations["cms_api_main_detail_view"]["responses"][200]["schema"]>>;
export declare const cms_api_main_pages_action_view: (id: string, headers: any, _apiPrefix?: string) => Promise<AxiosResponse<operations["cms_api_main_pages_action_view"]["responses"][201]["schema"]>>;
