/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/address/": {
    get: operations["address_list"];
    post: operations["address_create"];
    parameters: {};
  };
  "/address/{id}/": {
    get: operations["address_read"];
    put: operations["address_update"];
    delete: operations["address_delete"];
    patch: operations["address_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this address. */
        id: number;
      };
    };
  };
  "/answers/": {
    get: operations["answers_list"];
    post: operations["answers_create"];
    parameters: {};
  };
  "/answers/{id}/": {
    get: operations["answers_read"];
    put: operations["answers_update"];
    delete: operations["answers_delete"];
    patch: operations["answers_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this answers. */
        id: number;
      };
    };
  };
  "/app/": {
    get: operations["app_list"];
    post: operations["app_create"];
    parameters: {};
  };
  "/app/{id}/": {
    get: operations["app_read"];
    put: operations["app_update"];
    delete: operations["app_delete"];
    patch: operations["app_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this app. */
        id: number;
      };
    };
  };
  "/auth/login/": {
    post: operations["auth_login"];
    parameters: {};
  };
  "/comment/": {
    get: operations["comment_list"];
    post: operations["comment_create"];
    parameters: {};
  };
  "/comment/{id}/": {
    get: operations["comment_read"];
    put: operations["comment_update"];
    delete: operations["comment_delete"];
    patch: operations["comment_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this comment. */
        id: number;
      };
    };
  };
  "/condition/": {
    get: operations["condition_list"];
    post: operations["condition_create"];
    parameters: {};
  };
  "/condition/{id}/": {
    get: operations["condition_read"];
    put: operations["condition_update"];
    delete: operations["condition_delete"];
    patch: operations["condition_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this condition. */
        id: number;
      };
    };
  };
  "/department/": {
    get: operations["department_list"];
    post: operations["department_create"];
    parameters: {};
  };
  "/department/{id}/": {
    get: operations["department_read"];
    put: operations["department_update"];
    delete: operations["department_delete"];
    patch: operations["department_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this department. */
        id: number;
      };
    };
  };
  "/expertise/": {
    get: operations["expertise_list"];
    post: operations["expertise_create"];
    parameters: {};
  };
  "/expertise/{id}/": {
    get: operations["expertise_read"];
    put: operations["expertise_update"];
    delete: operations["expertise_delete"];
    patch: operations["expertise_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this expertise. */
        id: number;
      };
    };
  };
  "/expertiseprofile/": {
    get: operations["expertiseprofile_list"];
    post: operations["expertiseprofile_create"];
    parameters: {};
  };
  "/expertiseprofile/{id}/": {
    get: operations["expertiseprofile_read"];
    put: operations["expertiseprofile_update"];
    delete: operations["expertiseprofile_delete"];
    patch: operations["expertiseprofile_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this expertise profile. */
        id: number;
      };
    };
  };
  "/function/": {
    get: operations["function_list"];
    post: operations["function_create"];
    parameters: {};
  };
  "/function/{id}/": {
    get: operations["function_read"];
    put: operations["function_update"];
    delete: operations["function_delete"];
    patch: operations["function_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this function. */
        id: number;
      };
    };
  };
  "/newsletter/": {
    get: operations["newsletter_list"];
    post: operations["newsletter_create"];
    parameters: {};
  };
  "/newsletter/{id}/": {
    get: operations["newsletter_read"];
    put: operations["newsletter_update"];
    delete: operations["newsletter_delete"];
    patch: operations["newsletter_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this news letter. */
        id: number;
      };
    };
  };
  "/newsrelatedlink/": {
    get: operations["newsrelatedlink_list"];
    post: operations["newsrelatedlink_create"];
    parameters: {};
  };
  "/newsrelatedlink/{id}/": {
    get: operations["newsrelatedlink_read"];
    put: operations["newsrelatedlink_update"];
    delete: operations["newsrelatedlink_delete"];
    patch: operations["newsrelatedlink_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this news related link. */
        id: number;
      };
    };
  };
  "/person/": {
    get: operations["person_list"];
    post: operations["person_create"];
    parameters: {};
  };
  "/person/{id}/": {
    get: operations["person_read"];
    put: operations["person_update"];
    delete: operations["person_delete"];
    patch: operations["person_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this person. */
        id: number;
      };
    };
  };
  "/personlog/": {
    get: operations["personlog_list"];
    post: operations["personlog_create"];
    parameters: {};
  };
  "/personlog/{id}/": {
    get: operations["personlog_read"];
    put: operations["personlog_update"];
    delete: operations["personlog_delete"];
    patch: operations["personlog_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this person log. */
        id: number;
      };
    };
  };
  "/personstage/": {
    get: operations["personstage_list"];
    post: operations["personstage_create"];
    parameters: {};
  };
  "/personstage/{id}/": {
    get: operations["personstage_read"];
    put: operations["personstage_update"];
    delete: operations["personstage_delete"];
    patch: operations["personstage_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this person stage. */
        id: number;
      };
    };
  };
  "/phone/": {
    get: operations["phone_list"];
    post: operations["phone_create"];
    parameters: {};
  };
  "/phone/{id}/": {
    get: operations["phone_read"];
    put: operations["phone_update"];
    delete: operations["phone_delete"];
    patch: operations["phone_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this phone. */
        id: number;
      };
    };
  };
  "/question/": {
    get: operations["question_list"];
    post: operations["question_create"];
    parameters: {};
  };
  "/question/{id}/": {
    get: operations["question_read"];
    put: operations["question_update"];
    delete: operations["question_delete"];
    patch: operations["question_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this question. */
        id: number;
      };
    };
  };
  "/questionsrelatedlink/": {
    get: operations["questionsrelatedlink_list"];
    post: operations["questionsrelatedlink_create"];
    parameters: {};
  };
  "/questionsrelatedlink/{id}/": {
    get: operations["questionsrelatedlink_read"];
    put: operations["questionsrelatedlink_update"];
    delete: operations["questionsrelatedlink_delete"];
    patch: operations["questionsrelatedlink_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this questions related link. */
        id: number;
      };
    };
  };
  "/role/": {
    get: operations["role_list"];
    post: operations["role_create"];
    parameters: {};
  };
  "/role/{id}/": {
    get: operations["role_read"];
    put: operations["role_update"];
    delete: operations["role_delete"];
    patch: operations["role_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this role. */
        id: number;
      };
    };
  };
  "/staff/": {
    get: operations["staff_list"];
    post: operations["staff_create"];
    parameters: {};
  };
  "/staff/{id}/": {
    get: operations["staff_read"];
    put: operations["staff_update"];
    delete: operations["staff_delete"];
    patch: operations["staff_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this staff. */
        id: number;
      };
    };
  };
  "/staffcomment/": {
    get: operations["staffcomment_list"];
    post: operations["staffcomment_create"];
    parameters: {};
  };
  "/staffcomment/{id}/": {
    get: operations["staffcomment_read"];
    put: operations["staffcomment_update"];
    delete: operations["staffcomment_delete"];
    patch: operations["staffcomment_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this staff comment. */
        id: number;
      };
    };
  };
  "/stafffunctions/": {
    get: operations["stafffunctions_list"];
    post: operations["stafffunctions_create"];
    parameters: {};
  };
  "/stafffunctions/{id}/": {
    get: operations["stafffunctions_read"];
    put: operations["stafffunctions_update"];
    delete: operations["stafffunctions_delete"];
    patch: operations["stafffunctions_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this staff functions. */
        id: number;
      };
    };
  };
  "/stafflog/": {
    get: operations["stafflog_list"];
    post: operations["stafflog_create"];
    parameters: {};
  };
  "/stafflog/{id}/": {
    get: operations["stafflog_read"];
    put: operations["stafflog_update"];
    delete: operations["stafflog_delete"];
    patch: operations["stafflog_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this staff log. */
        id: number;
      };
    };
  };
  "/staffstage/": {
    get: operations["staffstage_list"];
    post: operations["staffstage_create"];
    parameters: {};
  };
  "/staffstage/{id}/": {
    get: operations["staffstage_read"];
    put: operations["staffstage_update"];
    delete: operations["staffstage_delete"];
    patch: operations["staffstage_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this staff stage. */
        id: number;
      };
    };
  };
  "/user/": {
    get: operations["user_list"];
    post: operations["user_create"];
    parameters: {};
  };
  "/user/{id}/": {
    get: operations["user_read"];
    put: operations["user_update"];
    delete: operations["user_delete"];
    patch: operations["user_partial_update"];
    parameters: {
      path: {
        /** A unique integer value identifying this user. */
        id: number;
      };
    };
  };
}

export interface definitions {
  Address: {
    /** ID */
    id?: number;
    /** Person */
    person: number;
    /** Description */
    description?: string;
    /** Address1 */
    address1?: string;
    /** Address2 */
    address2?: string;
    /** Zip */
    zip?: string;
    /** City */
    city?: string;
    /** Country */
    country?: string;
    /** Status */
    status: "activated" | "deactivated" | "pending" | "confirmed" | "archived";
    /**
     * Created date time
     * Format: date-time
     */
    created_date_time?: string;
  };
  answers: {
    /** ID */
    id?: number;
    /** Name */
    name?: string;
    /** Html */
    html?: string;
    /** Autor */
    autor: number;
    /** Status */
    status: "activated" | "deactivated" | "pending" | "confirmed" | "archived";
    /**
     * Created date time
     * Format: date-time
     */
    created_date_time?: string;
    /** Question */
    question: number;
  };
  App: {
    /** ID */
    id?: number;
    /** Title */
    title: string;
    /** PathUrl */
    pathUrl: string;
  };
  User: {
    /** ID */
    id?: number;
    /**
     * Email address
     * Format: email
     */
    email: string;
    /** Password */
    password: string;
    /** First name */
    first_name: string;
    /** Last name */
    last_name: string;
    /** Is active */
    is_active?: boolean;
  };
  Comment: {
    /** ID */
    id?: number;
    /** Name */
    name?: string;
    /** Html */
    html?: string;
    /** Autor */
    autor: number;
    /** Status */
    status: "activated" | "deactivated" | "pending" | "confirmed" | "archived";
    /**
     * Created date time
     * Format: date-time
     */
    created_date_time?: string;
    /** News */
    news: number;
  };
  Condition: {
    /** ID */
    id?: number;
    /** Severity */
    severity: "small" | "mild" | "sever";
    /** Status */
    status: "activated" | "deactivated" | "pending" | "confirmed" | "archived";
    /**
     * Created date time
     * Format: date-time
     */
    created_date_time?: string;
  };
  Department: {
    /** ID */
    id?: number;
    /** Name */
    name?: string;
    /** ParentId */
    parentId?: number;
    /** Description */
    description?: string;
    /** Shape */
    shape: "circle" | "square" | "rectangle" | "triangle";
    /** Status */
    status: "activated" | "deactivated" | "pending" | "confirmed" | "archived";
    /**
     * Created date time
     * Format: date-time
     */
    created_date_time?: string;
  };
  Expertise: {
    /** ID */
    id?: number;
    /** Name */
    name?: string;
    /** Description */
    description?: string;
    /** ParentId */
    parentId?: number;
    /** Status */
    status: "activated" | "deactivated" | "pending" | "confirmed" | "archived";
    /**
     * Created date time
     * Format: date-time
     */
    created_date_time?: string;
  };
  ExpertiseProfile: {
    /** ID */
    id?: number;
    /** Name */
    name?: string;
    /** Description */
    description?: string;
    /** Person */
    person: number;
    /** Expertise */
    expertise: number;
    /** Status */
    status: "activated" | "deactivated" | "pending" | "confirmed" | "archived";
    /**
     * Created date time
     * Format: date-time
     */
    created_date_time?: string;
  };
  Function: {
    /** ID */
    id?: number;
    /** Name */
    name?: string;
    /** Description */
    description?: string;
    /** Shape */
    shape: "circle" | "square" | "rectangle" | "triangle";
    /** Status */
    status: "activated" | "deactivated" | "pending" | "confirmed" | "archived";
    /**
     * Created date time
     * Format: date-time
     */
    created_date_time?: string;
  };
  NewsLetter: {
    /** ID */
    id?: number;
    /** Name */
    name?: string;
    /** Description */
    description?: string;
    /** Html */
    html?: string;
    /** Autor */
    autor: number;
    /** Status */
    status: "activated" | "deactivated" | "pending" | "confirmed" | "archived";
    /**
     * Created date time
     * Format: date-time
     */
    created_date_time?: string;
  };
  NewsRelatedLink: {
    /** ID */
    id?: number;
    /** News */
    news: number;
    /** Name */
    name?: string;
    /**
     * Created date time
     * Format: date-time
     */
    created_date_time?: string;
  };
  Person: {
    /** ID */
    id?: number;
    /** Firstname */
    firstname?: string;
    /** Lastname */
    lastname?: string;
    /** Age */
    age: number;
    /** NationalId */
    nationalId?: string;
    /** Status */
    status: "activated" | "deactivated" | "pending" | "confirmed" | "archived";
    /**
     * Created date time
     * Format: date-time
     */
    created_date_time?: string;
  };
  PersonLog: {
    /** ID */
    id?: number;
    /** Description */
    description?: string;
    /** Stage */
    stage: number;
    /** Person */
    person: number;
    /** Status */
    status: "activated" | "deactivated" | "pending" | "confirmed" | "archived";
    /**
     * Created date time
     * Format: date-time
     */
    created_date_time?: string;
  };
  PersonStage: {
    /** ID */
    id?: number;
    /** Name */
    name?: string;
    /** Description */
    description?: string;
    /** Step */
    step:
      | "communication"
      | "answers"
      | "pending"
      | "interview"
      | "contract"
      | "rejection"
      | "refusal"
      | "recommendation"
      | "questions"
      | "invitations";
    /** X */
    x: number;
    /** Status */
    status: "activated" | "deactivated" | "pending" | "confirmed" | "archived";
    /**
     * Created date time
     * Format: date-time
     */
    created_date_time?: string;
  };
  Phone: {
    /** ID */
    id?: number;
    /** Person */
    person: number;
    /** Description */
    description?: string;
    /** PhoneNumber */
    phoneNumber?: string;
    /** Status */
    status: "activated" | "deactivated" | "pending" | "confirmed" | "archived";
    /**
     * Created date time
     * Format: date-time
     */
    created_date_time?: string;
  };
  Question: {
    /** ID */
    id?: number;
    /** Name */
    name?: string;
    /** Html */
    html?: string;
    /** Description */
    description?: string;
    /** Autor */
    autor: number;
    /** Status */
    status: "activated" | "deactivated" | "pending" | "confirmed" | "archived";
    /**
     * Created date time
     * Format: date-time
     */
    created_date_time?: string;
  };
  QuestionsRelatedLink: {
    /** ID */
    id?: number;
    /** Question */
    question: number;
    /** Name */
    name?: string;
    /**
     * Created date time
     * Format: date-time
     */
    created_date_time?: string;
  };
  Role: {
    /** ID */
    id?: number;
    /** Title */
    title: string;
    /** User */
    user: number;
    /** Permission */
    permission?: "R" | "W" | "RW" | "RWD";
    /** App */
    app: number;
  };
  Staff: {
    /** ID */
    id?: number;
    /** Department */
    department: number;
    /** Condition */
    condition: number;
    /** Title */
    title?: string;
    /** BossId */
    bossId?: number;
    /** Who */
    who: number;
    /** X */
    x: number;
    /** Y */
    y: number;
    /** Level */
    level: number;
  };
  StaffComment: {
    /** ID */
    id?: number;
    /** Staff */
    staff: number;
    /** Name */
    name?: string;
    /** Description */
    description?: string;
    /** Status */
    status: "activated" | "deactivated" | "pending" | "confirmed" | "archived";
    /**
     * Created date time
     * Format: date-time
     */
    created_date_time?: string;
  };
  StaffFunctions: {
    /** ID */
    id?: number;
    /** Function */
    function: number;
    /** Staff */
    staff: number;
    /** Status */
    status: "activated" | "deactivated" | "pending" | "confirmed" | "archived";
    /**
     * Created date time
     * Format: date-time
     */
    created_date_time?: string;
  };
  StaffLog: {
    /** ID */
    id?: number;
    /** Description */
    description?: string;
    /** Stage */
    stage: number;
    /** With person */
    with_person?: number;
    /** Status */
    status: "activated" | "deactivated" | "pending" | "confirmed" | "archived";
    /**
     * Created date time
     * Format: date-time
     */
    created_date_time?: string;
  };
  StaffStage: {
    /** ID */
    id?: number;
    /** Name */
    name?: string;
    /** Description */
    description?: string;
    /** Step */
    step:
      | "communication"
      | "answers"
      | "meeting"
      | "surveys"
      | "administrative"
      | "complains"
      | "problems"
      | "feedBack"
      | "requirements"
      | "legal"
      | "questions"
      | "gifts"
      | "invitations";
    /** X */
    x: number;
    /** Status */
    status: "activated" | "deactivated" | "pending" | "confirmed" | "archived";
    /**
     * Created date time
     * Format: date-time
     */
    created_date_time?: string;
  };
}

export interface operations {
  address_list: {
    parameters: {
      query: {
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["Address"][];
        };
      };
    };
  };
  address_create: {
    parameters: {
      body: {
        data: definitions["Address"];
      };
    };
    responses: {
      201: {
        schema: definitions["Address"];
      };
    };
  };
  address_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this address. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["Address"];
      };
    };
  };
  address_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this address. */
        id: number;
      };
      body: {
        data: definitions["Address"];
      };
    };
    responses: {
      200: {
        schema: definitions["Address"];
      };
    };
  };
  address_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this address. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  address_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this address. */
        id: number;
      };
      body: {
        data: definitions["Address"];
      };
    };
    responses: {
      200: {
        schema: definitions["Address"];
      };
    };
  };
  answers_list: {
    parameters: {
      query: {
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["answers"][];
        };
      };
    };
  };
  answers_create: {
    parameters: {
      body: {
        data: definitions["answers"];
      };
    };
    responses: {
      201: {
        schema: definitions["answers"];
      };
    };
  };
  answers_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this answers. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["answers"];
      };
    };
  };
  answers_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this answers. */
        id: number;
      };
      body: {
        data: definitions["answers"];
      };
    };
    responses: {
      200: {
        schema: definitions["answers"];
      };
    };
  };
  answers_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this answers. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  answers_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this answers. */
        id: number;
      };
      body: {
        data: definitions["answers"];
      };
    };
    responses: {
      200: {
        schema: definitions["answers"];
      };
    };
  };
  app_list: {
    parameters: {
      query: {
        id?: number;
        title?: string;
        pathUrl?: string;
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["App"][];
        };
      };
    };
  };
  app_create: {
    parameters: {
      body: {
        data: definitions["App"];
      };
    };
    responses: {
      201: {
        schema: definitions["App"];
      };
    };
  };
  app_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this app. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["App"];
      };
    };
  };
  app_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this app. */
        id: number;
      };
      body: {
        data: definitions["App"];
      };
    };
    responses: {
      200: {
        schema: definitions["App"];
      };
    };
  };
  app_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this app. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  app_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this app. */
        id: number;
      };
      body: {
        data: definitions["App"];
      };
    };
    responses: {
      200: {
        schema: definitions["App"];
      };
    };
  };
  auth_login: {
    parameters: {
      body: {
        data: definitions["User"];
      };
    };
    responses: {
      /** Login successful */
      201: {
        schema: definitions["User"];
      };
    };
  };
  comment_list: {
    parameters: {
      query: {
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["Comment"][];
        };
      };
    };
  };
  comment_create: {
    parameters: {
      body: {
        data: definitions["Comment"];
      };
    };
    responses: {
      201: {
        schema: definitions["Comment"];
      };
    };
  };
  comment_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this comment. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["Comment"];
      };
    };
  };
  comment_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this comment. */
        id: number;
      };
      body: {
        data: definitions["Comment"];
      };
    };
    responses: {
      200: {
        schema: definitions["Comment"];
      };
    };
  };
  comment_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this comment. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  comment_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this comment. */
        id: number;
      };
      body: {
        data: definitions["Comment"];
      };
    };
    responses: {
      200: {
        schema: definitions["Comment"];
      };
    };
  };
  condition_list: {
    parameters: {
      query: {
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["Condition"][];
        };
      };
    };
  };
  condition_create: {
    parameters: {
      body: {
        data: definitions["Condition"];
      };
    };
    responses: {
      201: {
        schema: definitions["Condition"];
      };
    };
  };
  condition_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this condition. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["Condition"];
      };
    };
  };
  condition_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this condition. */
        id: number;
      };
      body: {
        data: definitions["Condition"];
      };
    };
    responses: {
      200: {
        schema: definitions["Condition"];
      };
    };
  };
  condition_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this condition. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  condition_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this condition. */
        id: number;
      };
      body: {
        data: definitions["Condition"];
      };
    };
    responses: {
      200: {
        schema: definitions["Condition"];
      };
    };
  };
  department_list: {
    parameters: {
      query: {
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["Department"][];
        };
      };
    };
  };
  department_create: {
    parameters: {
      body: {
        data: definitions["Department"];
      };
    };
    responses: {
      201: {
        schema: definitions["Department"];
      };
    };
  };
  department_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this department. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["Department"];
      };
    };
  };
  department_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this department. */
        id: number;
      };
      body: {
        data: definitions["Department"];
      };
    };
    responses: {
      200: {
        schema: definitions["Department"];
      };
    };
  };
  department_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this department. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  department_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this department. */
        id: number;
      };
      body: {
        data: definitions["Department"];
      };
    };
    responses: {
      200: {
        schema: definitions["Department"];
      };
    };
  };
  expertise_list: {
    parameters: {
      query: {
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["Expertise"][];
        };
      };
    };
  };
  expertise_create: {
    parameters: {
      body: {
        data: definitions["Expertise"];
      };
    };
    responses: {
      201: {
        schema: definitions["Expertise"];
      };
    };
  };
  expertise_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this expertise. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["Expertise"];
      };
    };
  };
  expertise_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this expertise. */
        id: number;
      };
      body: {
        data: definitions["Expertise"];
      };
    };
    responses: {
      200: {
        schema: definitions["Expertise"];
      };
    };
  };
  expertise_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this expertise. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  expertise_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this expertise. */
        id: number;
      };
      body: {
        data: definitions["Expertise"];
      };
    };
    responses: {
      200: {
        schema: definitions["Expertise"];
      };
    };
  };
  expertiseprofile_list: {
    parameters: {
      query: {
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["ExpertiseProfile"][];
        };
      };
    };
  };
  expertiseprofile_create: {
    parameters: {
      body: {
        data: definitions["ExpertiseProfile"];
      };
    };
    responses: {
      201: {
        schema: definitions["ExpertiseProfile"];
      };
    };
  };
  expertiseprofile_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this expertise profile. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["ExpertiseProfile"];
      };
    };
  };
  expertiseprofile_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this expertise profile. */
        id: number;
      };
      body: {
        data: definitions["ExpertiseProfile"];
      };
    };
    responses: {
      200: {
        schema: definitions["ExpertiseProfile"];
      };
    };
  };
  expertiseprofile_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this expertise profile. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  expertiseprofile_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this expertise profile. */
        id: number;
      };
      body: {
        data: definitions["ExpertiseProfile"];
      };
    };
    responses: {
      200: {
        schema: definitions["ExpertiseProfile"];
      };
    };
  };
  function_list: {
    parameters: {
      query: {
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["Function"][];
        };
      };
    };
  };
  function_create: {
    parameters: {
      body: {
        data: definitions["Function"];
      };
    };
    responses: {
      201: {
        schema: definitions["Function"];
      };
    };
  };
  function_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this function. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["Function"];
      };
    };
  };
  function_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this function. */
        id: number;
      };
      body: {
        data: definitions["Function"];
      };
    };
    responses: {
      200: {
        schema: definitions["Function"];
      };
    };
  };
  function_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this function. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  function_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this function. */
        id: number;
      };
      body: {
        data: definitions["Function"];
      };
    };
    responses: {
      200: {
        schema: definitions["Function"];
      };
    };
  };
  newsletter_list: {
    parameters: {
      query: {
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["NewsLetter"][];
        };
      };
    };
  };
  newsletter_create: {
    parameters: {
      body: {
        data: definitions["NewsLetter"];
      };
    };
    responses: {
      201: {
        schema: definitions["NewsLetter"];
      };
    };
  };
  newsletter_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this news letter. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["NewsLetter"];
      };
    };
  };
  newsletter_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this news letter. */
        id: number;
      };
      body: {
        data: definitions["NewsLetter"];
      };
    };
    responses: {
      200: {
        schema: definitions["NewsLetter"];
      };
    };
  };
  newsletter_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this news letter. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  newsletter_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this news letter. */
        id: number;
      };
      body: {
        data: definitions["NewsLetter"];
      };
    };
    responses: {
      200: {
        schema: definitions["NewsLetter"];
      };
    };
  };
  newsrelatedlink_list: {
    parameters: {
      query: {
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["NewsRelatedLink"][];
        };
      };
    };
  };
  newsrelatedlink_create: {
    parameters: {
      body: {
        data: definitions["NewsRelatedLink"];
      };
    };
    responses: {
      201: {
        schema: definitions["NewsRelatedLink"];
      };
    };
  };
  newsrelatedlink_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this news related link. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["NewsRelatedLink"];
      };
    };
  };
  newsrelatedlink_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this news related link. */
        id: number;
      };
      body: {
        data: definitions["NewsRelatedLink"];
      };
    };
    responses: {
      200: {
        schema: definitions["NewsRelatedLink"];
      };
    };
  };
  newsrelatedlink_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this news related link. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  newsrelatedlink_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this news related link. */
        id: number;
      };
      body: {
        data: definitions["NewsRelatedLink"];
      };
    };
    responses: {
      200: {
        schema: definitions["NewsRelatedLink"];
      };
    };
  };
  person_list: {
    parameters: {
      query: {
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["Person"][];
        };
      };
    };
  };
  person_create: {
    parameters: {
      body: {
        data: definitions["Person"];
      };
    };
    responses: {
      201: {
        schema: definitions["Person"];
      };
    };
  };
  person_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this person. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["Person"];
      };
    };
  };
  person_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this person. */
        id: number;
      };
      body: {
        data: definitions["Person"];
      };
    };
    responses: {
      200: {
        schema: definitions["Person"];
      };
    };
  };
  person_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this person. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  person_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this person. */
        id: number;
      };
      body: {
        data: definitions["Person"];
      };
    };
    responses: {
      200: {
        schema: definitions["Person"];
      };
    };
  };
  personlog_list: {
    parameters: {
      query: {
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["PersonLog"][];
        };
      };
    };
  };
  personlog_create: {
    parameters: {
      body: {
        data: definitions["PersonLog"];
      };
    };
    responses: {
      201: {
        schema: definitions["PersonLog"];
      };
    };
  };
  personlog_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this person log. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["PersonLog"];
      };
    };
  };
  personlog_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this person log. */
        id: number;
      };
      body: {
        data: definitions["PersonLog"];
      };
    };
    responses: {
      200: {
        schema: definitions["PersonLog"];
      };
    };
  };
  personlog_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this person log. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  personlog_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this person log. */
        id: number;
      };
      body: {
        data: definitions["PersonLog"];
      };
    };
    responses: {
      200: {
        schema: definitions["PersonLog"];
      };
    };
  };
  personstage_list: {
    parameters: {
      query: {
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["PersonStage"][];
        };
      };
    };
  };
  personstage_create: {
    parameters: {
      body: {
        data: definitions["PersonStage"];
      };
    };
    responses: {
      201: {
        schema: definitions["PersonStage"];
      };
    };
  };
  personstage_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this person stage. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["PersonStage"];
      };
    };
  };
  personstage_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this person stage. */
        id: number;
      };
      body: {
        data: definitions["PersonStage"];
      };
    };
    responses: {
      200: {
        schema: definitions["PersonStage"];
      };
    };
  };
  personstage_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this person stage. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  personstage_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this person stage. */
        id: number;
      };
      body: {
        data: definitions["PersonStage"];
      };
    };
    responses: {
      200: {
        schema: definitions["PersonStage"];
      };
    };
  };
  phone_list: {
    parameters: {
      query: {
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["Phone"][];
        };
      };
    };
  };
  phone_create: {
    parameters: {
      body: {
        data: definitions["Phone"];
      };
    };
    responses: {
      201: {
        schema: definitions["Phone"];
      };
    };
  };
  phone_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this phone. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["Phone"];
      };
    };
  };
  phone_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this phone. */
        id: number;
      };
      body: {
        data: definitions["Phone"];
      };
    };
    responses: {
      200: {
        schema: definitions["Phone"];
      };
    };
  };
  phone_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this phone. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  phone_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this phone. */
        id: number;
      };
      body: {
        data: definitions["Phone"];
      };
    };
    responses: {
      200: {
        schema: definitions["Phone"];
      };
    };
  };
  question_list: {
    parameters: {
      query: {
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["Question"][];
        };
      };
    };
  };
  question_create: {
    parameters: {
      body: {
        data: definitions["Question"];
      };
    };
    responses: {
      201: {
        schema: definitions["Question"];
      };
    };
  };
  question_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this question. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["Question"];
      };
    };
  };
  question_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this question. */
        id: number;
      };
      body: {
        data: definitions["Question"];
      };
    };
    responses: {
      200: {
        schema: definitions["Question"];
      };
    };
  };
  question_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this question. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  question_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this question. */
        id: number;
      };
      body: {
        data: definitions["Question"];
      };
    };
    responses: {
      200: {
        schema: definitions["Question"];
      };
    };
  };
  questionsrelatedlink_list: {
    parameters: {
      query: {
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["QuestionsRelatedLink"][];
        };
      };
    };
  };
  questionsrelatedlink_create: {
    parameters: {
      body: {
        data: definitions["QuestionsRelatedLink"];
      };
    };
    responses: {
      201: {
        schema: definitions["QuestionsRelatedLink"];
      };
    };
  };
  questionsrelatedlink_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this questions related link. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["QuestionsRelatedLink"];
      };
    };
  };
  questionsrelatedlink_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this questions related link. */
        id: number;
      };
      body: {
        data: definitions["QuestionsRelatedLink"];
      };
    };
    responses: {
      200: {
        schema: definitions["QuestionsRelatedLink"];
      };
    };
  };
  questionsrelatedlink_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this questions related link. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  questionsrelatedlink_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this questions related link. */
        id: number;
      };
      body: {
        data: definitions["QuestionsRelatedLink"];
      };
    };
    responses: {
      200: {
        schema: definitions["QuestionsRelatedLink"];
      };
    };
  };
  role_list: {
    parameters: {
      query: {
        id?: number;
        title?: string;
        user?: string;
        permission?: string;
        app?: string;
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["Role"][];
        };
      };
    };
  };
  role_create: {
    parameters: {
      body: {
        data: definitions["Role"];
      };
    };
    responses: {
      201: {
        schema: definitions["Role"];
      };
    };
  };
  role_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this role. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["Role"];
      };
    };
  };
  role_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this role. */
        id: number;
      };
      body: {
        data: definitions["Role"];
      };
    };
    responses: {
      200: {
        schema: definitions["Role"];
      };
    };
  };
  role_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this role. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  role_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this role. */
        id: number;
      };
      body: {
        data: definitions["Role"];
      };
    };
    responses: {
      200: {
        schema: definitions["Role"];
      };
    };
  };
  staff_list: {
    parameters: {
      query: {
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["Staff"][];
        };
      };
    };
  };
  staff_create: {
    parameters: {
      body: {
        data: definitions["Staff"];
      };
    };
    responses: {
      201: {
        schema: definitions["Staff"];
      };
    };
  };
  staff_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this staff. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["Staff"];
      };
    };
  };
  staff_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this staff. */
        id: number;
      };
      body: {
        data: definitions["Staff"];
      };
    };
    responses: {
      200: {
        schema: definitions["Staff"];
      };
    };
  };
  staff_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this staff. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  staff_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this staff. */
        id: number;
      };
      body: {
        data: definitions["Staff"];
      };
    };
    responses: {
      200: {
        schema: definitions["Staff"];
      };
    };
  };
  staffcomment_list: {
    parameters: {
      query: {
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["StaffComment"][];
        };
      };
    };
  };
  staffcomment_create: {
    parameters: {
      body: {
        data: definitions["StaffComment"];
      };
    };
    responses: {
      201: {
        schema: definitions["StaffComment"];
      };
    };
  };
  staffcomment_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this staff comment. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["StaffComment"];
      };
    };
  };
  staffcomment_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this staff comment. */
        id: number;
      };
      body: {
        data: definitions["StaffComment"];
      };
    };
    responses: {
      200: {
        schema: definitions["StaffComment"];
      };
    };
  };
  staffcomment_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this staff comment. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  staffcomment_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this staff comment. */
        id: number;
      };
      body: {
        data: definitions["StaffComment"];
      };
    };
    responses: {
      200: {
        schema: definitions["StaffComment"];
      };
    };
  };
  stafffunctions_list: {
    parameters: {
      query: {
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["StaffFunctions"][];
        };
      };
    };
  };
  stafffunctions_create: {
    parameters: {
      body: {
        data: definitions["StaffFunctions"];
      };
    };
    responses: {
      201: {
        schema: definitions["StaffFunctions"];
      };
    };
  };
  stafffunctions_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this staff functions. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["StaffFunctions"];
      };
    };
  };
  stafffunctions_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this staff functions. */
        id: number;
      };
      body: {
        data: definitions["StaffFunctions"];
      };
    };
    responses: {
      200: {
        schema: definitions["StaffFunctions"];
      };
    };
  };
  stafffunctions_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this staff functions. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  stafffunctions_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this staff functions. */
        id: number;
      };
      body: {
        data: definitions["StaffFunctions"];
      };
    };
    responses: {
      200: {
        schema: definitions["StaffFunctions"];
      };
    };
  };
  stafflog_list: {
    parameters: {
      query: {
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["StaffLog"][];
        };
      };
    };
  };
  stafflog_create: {
    parameters: {
      body: {
        data: definitions["StaffLog"];
      };
    };
    responses: {
      201: {
        schema: definitions["StaffLog"];
      };
    };
  };
  stafflog_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this staff log. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["StaffLog"];
      };
    };
  };
  stafflog_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this staff log. */
        id: number;
      };
      body: {
        data: definitions["StaffLog"];
      };
    };
    responses: {
      200: {
        schema: definitions["StaffLog"];
      };
    };
  };
  stafflog_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this staff log. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  stafflog_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this staff log. */
        id: number;
      };
      body: {
        data: definitions["StaffLog"];
      };
    };
    responses: {
      200: {
        schema: definitions["StaffLog"];
      };
    };
  };
  staffstage_list: {
    parameters: {
      query: {
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["StaffStage"][];
        };
      };
    };
  };
  staffstage_create: {
    parameters: {
      body: {
        data: definitions["StaffStage"];
      };
    };
    responses: {
      201: {
        schema: definitions["StaffStage"];
      };
    };
  };
  staffstage_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this staff stage. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["StaffStage"];
      };
    };
  };
  staffstage_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this staff stage. */
        id: number;
      };
      body: {
        data: definitions["StaffStage"];
      };
    };
    responses: {
      200: {
        schema: definitions["StaffStage"];
      };
    };
  };
  staffstage_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this staff stage. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  staffstage_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this staff stage. */
        id: number;
      };
      body: {
        data: definitions["StaffStage"];
      };
    };
    responses: {
      200: {
        schema: definitions["StaffStage"];
      };
    };
  };
  user_list: {
    parameters: {
      query: {
        id?: number;
        email?: string;
        password?: string;
        first_name?: string;
        last_name?: string;
        is_active?: string;
        /** A page number within the paginated result set. */
        page?: number;
        /** Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        schema: {
          count: number;
          /** Format: uri */
          next?: string;
          /** Format: uri */
          previous?: string;
          results: definitions["User"][];
        };
      };
    };
  };
  user_create: {
    parameters: {
      body: {
        data: definitions["User"];
      };
    };
    responses: {
      201: {
        schema: definitions["User"];
      };
    };
  };
  user_read: {
    parameters: {
      path: {
        /** A unique integer value identifying this user. */
        id: number;
      };
    };
    responses: {
      200: {
        schema: definitions["User"];
      };
    };
  };
  user_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this user. */
        id: number;
      };
      body: {
        data: definitions["User"];
      };
    };
    responses: {
      200: {
        schema: definitions["User"];
      };
    };
  };
  user_delete: {
    parameters: {
      path: {
        /** A unique integer value identifying this user. */
        id: number;
      };
    };
    responses: {
      204: never;
    };
  };
  user_partial_update: {
    parameters: {
      path: {
        /** A unique integer value identifying this user. */
        id: number;
      };
      body: {
        data: definitions["User"];
      };
    };
    responses: {
      200: {
        schema: definitions["User"];
      };
    };
  };
}

export interface external {}
