import { AddressResource } from './Address';
import { answersResource } from './answers';
import { AppResource } from './App';
import { LoginResource } from './Login';
import { CommentResource } from './Comment';
import { ConditionResource } from './Condition';
import { DepartmentResource } from './Department';
import { ExpertiseResource } from './Expertise';
import { ExpertiseProfileResource } from './ExpertiseProfile';
import { FunctionResource } from './Function';
import { NewsLetterResource } from './NewsLetter';
import { NewsRelatedLinkResource } from './NewsRelatedLink';
import { PersonResource } from './Person';
import { PersonLogResource } from './PersonLog';
import { PersonStageResource } from './PersonStage';
import { PhoneResource } from './Phone';
import { QuestionResource } from './Question';
import { QuestionsRelatedLinkResource } from './QuestionsRelatedLink';
import { RoleResource } from './Role';
import { StaffResource } from './Staff';
import { StaffCommentResource } from './StaffComment';
import { StaffFunctionsResource } from './StaffFunctions';
import { StaffLogResource } from './StaffLog';
import { StaffStageResource } from './StaffStage';
import { UserResource } from './User';
export { AddressResource, answersResource, AppResource, LoginResource, CommentResource, ConditionResource, DepartmentResource, ExpertiseResource, ExpertiseProfileResource, FunctionResource, NewsLetterResource, NewsRelatedLinkResource, PersonResource, PersonLogResource, PersonStageResource, PhoneResource, QuestionResource, QuestionsRelatedLinkResource, RoleResource, StaffResource, StaffCommentResource, StaffFunctionsResource, StaffLogResource, StaffStageResource, UserResource, };
//# sourceMappingURL=index.js.map