"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserResource = exports.StaffStageResource = exports.StaffLogResource = exports.StaffFunctionsResource = exports.StaffCommentResource = exports.StaffResource = exports.RoleResource = exports.QuestionsRelatedLinkResource = exports.QuestionResource = exports.PhoneResource = exports.PersonStageResource = exports.PersonLogResource = exports.PersonResource = exports.NewsRelatedLinkResource = exports.NewsLetterResource = exports.FunctionResource = exports.ExpertiseProfileResource = exports.ExpertiseResource = exports.DepartmentResource = exports.ConditionResource = exports.CommentResource = exports.AppResource = exports.answersResource = exports.AddressResource = void 0;
var Address_1 = require("./Address");
Object.defineProperty(exports, "AddressResource", { enumerable: true, get: function () { return Address_1.AddressResource; } });
var answers_1 = require("./answers");
Object.defineProperty(exports, "answersResource", { enumerable: true, get: function () { return answers_1.answersResource; } });
var App_1 = require("./App");
Object.defineProperty(exports, "AppResource", { enumerable: true, get: function () { return App_1.AppResource; } });
var Comment_1 = require("./Comment");
Object.defineProperty(exports, "CommentResource", { enumerable: true, get: function () { return Comment_1.CommentResource; } });
var Condition_1 = require("./Condition");
Object.defineProperty(exports, "ConditionResource", { enumerable: true, get: function () { return Condition_1.ConditionResource; } });
var Department_1 = require("./Department");
Object.defineProperty(exports, "DepartmentResource", { enumerable: true, get: function () { return Department_1.DepartmentResource; } });
var Expertise_1 = require("./Expertise");
Object.defineProperty(exports, "ExpertiseResource", { enumerable: true, get: function () { return Expertise_1.ExpertiseResource; } });
var ExpertiseProfile_1 = require("./ExpertiseProfile");
Object.defineProperty(exports, "ExpertiseProfileResource", { enumerable: true, get: function () { return ExpertiseProfile_1.ExpertiseProfileResource; } });
var Function_1 = require("./Function");
Object.defineProperty(exports, "FunctionResource", { enumerable: true, get: function () { return Function_1.FunctionResource; } });
var NewsLetter_1 = require("./NewsLetter");
Object.defineProperty(exports, "NewsLetterResource", { enumerable: true, get: function () { return NewsLetter_1.NewsLetterResource; } });
var NewsRelatedLink_1 = require("./NewsRelatedLink");
Object.defineProperty(exports, "NewsRelatedLinkResource", { enumerable: true, get: function () { return NewsRelatedLink_1.NewsRelatedLinkResource; } });
var Person_1 = require("./Person");
Object.defineProperty(exports, "PersonResource", { enumerable: true, get: function () { return Person_1.PersonResource; } });
var PersonLog_1 = require("./PersonLog");
Object.defineProperty(exports, "PersonLogResource", { enumerable: true, get: function () { return PersonLog_1.PersonLogResource; } });
var PersonStage_1 = require("./PersonStage");
Object.defineProperty(exports, "PersonStageResource", { enumerable: true, get: function () { return PersonStage_1.PersonStageResource; } });
var Phone_1 = require("./Phone");
Object.defineProperty(exports, "PhoneResource", { enumerable: true, get: function () { return Phone_1.PhoneResource; } });
var Question_1 = require("./Question");
Object.defineProperty(exports, "QuestionResource", { enumerable: true, get: function () { return Question_1.QuestionResource; } });
var QuestionsRelatedLink_1 = require("./QuestionsRelatedLink");
Object.defineProperty(exports, "QuestionsRelatedLinkResource", { enumerable: true, get: function () { return QuestionsRelatedLink_1.QuestionsRelatedLinkResource; } });
var Role_1 = require("./Role");
Object.defineProperty(exports, "RoleResource", { enumerable: true, get: function () { return Role_1.RoleResource; } });
var Staff_1 = require("./Staff");
Object.defineProperty(exports, "StaffResource", { enumerable: true, get: function () { return Staff_1.StaffResource; } });
var StaffComment_1 = require("./StaffComment");
Object.defineProperty(exports, "StaffCommentResource", { enumerable: true, get: function () { return StaffComment_1.StaffCommentResource; } });
var StaffFunctions_1 = require("./StaffFunctions");
Object.defineProperty(exports, "StaffFunctionsResource", { enumerable: true, get: function () { return StaffFunctions_1.StaffFunctionsResource; } });
var StaffLog_1 = require("./StaffLog");
Object.defineProperty(exports, "StaffLogResource", { enumerable: true, get: function () { return StaffLog_1.StaffLogResource; } });
var StaffStage_1 = require("./StaffStage");
Object.defineProperty(exports, "StaffStageResource", { enumerable: true, get: function () { return StaffStage_1.StaffStageResource; } });
var User_1 = require("./User");
Object.defineProperty(exports, "UserResource", { enumerable: true, get: function () { return User_1.UserResource; } });
//# sourceMappingURL=index.js.map