"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserContext = exports.UserProvider = exports.StaffstageContext = exports.StaffstageProvider = exports.StafflogContext = exports.StafflogProvider = exports.StafffunctionsContext = exports.StafffunctionsProvider = exports.StaffcommentContext = exports.StaffcommentProvider = exports.StaffContext = exports.StaffProvider = exports.RoleContext = exports.RoleProvider = exports.PhoneContext = exports.PhoneProvider = exports.PersonstageContext = exports.PersonstageProvider = exports.PersonlogContext = exports.PersonlogProvider = exports.PersonContext = exports.PersonProvider = exports.NewsrelatedlinkContext = exports.NewsrelatedlinkProvider = exports.NewsletterContext = exports.NewsletterProvider = exports.FunctionContext = exports.FunctionProvider = exports.ExpertiseprofileContext = exports.ExpertiseprofileProvider = exports.ExpertiseContext = exports.ExpertiseProvider = exports.DepartmentContext = exports.DepartmentProvider = exports.ConditionContext = exports.ConditionProvider = exports.CommentContext = exports.CommentProvider = exports.AppContext = exports.AppProvider = exports.AddressContext = exports.AddressProvider = void 0;
var address_1 = require("./address");
Object.defineProperty(exports, "AddressProvider", { enumerable: true, get: function () { return address_1.AddressProvider; } });
Object.defineProperty(exports, "AddressContext", { enumerable: true, get: function () { return address_1.AddressContext; } });
var app_1 = require("./app");
Object.defineProperty(exports, "AppProvider", { enumerable: true, get: function () { return app_1.AppProvider; } });
Object.defineProperty(exports, "AppContext", { enumerable: true, get: function () { return app_1.AppContext; } });
var comment_1 = require("./comment");
Object.defineProperty(exports, "CommentProvider", { enumerable: true, get: function () { return comment_1.CommentProvider; } });
Object.defineProperty(exports, "CommentContext", { enumerable: true, get: function () { return comment_1.CommentContext; } });
var condition_1 = require("./condition");
Object.defineProperty(exports, "ConditionProvider", { enumerable: true, get: function () { return condition_1.ConditionProvider; } });
Object.defineProperty(exports, "ConditionContext", { enumerable: true, get: function () { return condition_1.ConditionContext; } });
var department_1 = require("./department");
Object.defineProperty(exports, "DepartmentProvider", { enumerable: true, get: function () { return department_1.DepartmentProvider; } });
Object.defineProperty(exports, "DepartmentContext", { enumerable: true, get: function () { return department_1.DepartmentContext; } });
var expertise_1 = require("./expertise");
Object.defineProperty(exports, "ExpertiseProvider", { enumerable: true, get: function () { return expertise_1.ExpertiseProvider; } });
Object.defineProperty(exports, "ExpertiseContext", { enumerable: true, get: function () { return expertise_1.ExpertiseContext; } });
var expertiseprofile_1 = require("./expertiseprofile");
Object.defineProperty(exports, "ExpertiseprofileProvider", { enumerable: true, get: function () { return expertiseprofile_1.ExpertiseprofileProvider; } });
Object.defineProperty(exports, "ExpertiseprofileContext", { enumerable: true, get: function () { return expertiseprofile_1.ExpertiseprofileContext; } });
var function_1 = require("./function");
Object.defineProperty(exports, "FunctionProvider", { enumerable: true, get: function () { return function_1.FunctionProvider; } });
Object.defineProperty(exports, "FunctionContext", { enumerable: true, get: function () { return function_1.FunctionContext; } });
var newsletter_1 = require("./newsletter");
Object.defineProperty(exports, "NewsletterProvider", { enumerable: true, get: function () { return newsletter_1.NewsletterProvider; } });
Object.defineProperty(exports, "NewsletterContext", { enumerable: true, get: function () { return newsletter_1.NewsletterContext; } });
var newsrelatedlink_1 = require("./newsrelatedlink");
Object.defineProperty(exports, "NewsrelatedlinkProvider", { enumerable: true, get: function () { return newsrelatedlink_1.NewsrelatedlinkProvider; } });
Object.defineProperty(exports, "NewsrelatedlinkContext", { enumerable: true, get: function () { return newsrelatedlink_1.NewsrelatedlinkContext; } });
var person_1 = require("./person");
Object.defineProperty(exports, "PersonProvider", { enumerable: true, get: function () { return person_1.PersonProvider; } });
Object.defineProperty(exports, "PersonContext", { enumerable: true, get: function () { return person_1.PersonContext; } });
var personlog_1 = require("./personlog");
Object.defineProperty(exports, "PersonlogProvider", { enumerable: true, get: function () { return personlog_1.PersonlogProvider; } });
Object.defineProperty(exports, "PersonlogContext", { enumerable: true, get: function () { return personlog_1.PersonlogContext; } });
var personstage_1 = require("./personstage");
Object.defineProperty(exports, "PersonstageProvider", { enumerable: true, get: function () { return personstage_1.PersonstageProvider; } });
Object.defineProperty(exports, "PersonstageContext", { enumerable: true, get: function () { return personstage_1.PersonstageContext; } });
var phone_1 = require("./phone");
Object.defineProperty(exports, "PhoneProvider", { enumerable: true, get: function () { return phone_1.PhoneProvider; } });
Object.defineProperty(exports, "PhoneContext", { enumerable: true, get: function () { return phone_1.PhoneContext; } });
var role_1 = require("./role");
Object.defineProperty(exports, "RoleProvider", { enumerable: true, get: function () { return role_1.RoleProvider; } });
Object.defineProperty(exports, "RoleContext", { enumerable: true, get: function () { return role_1.RoleContext; } });
var staff_1 = require("./staff");
Object.defineProperty(exports, "StaffProvider", { enumerable: true, get: function () { return staff_1.StaffProvider; } });
Object.defineProperty(exports, "StaffContext", { enumerable: true, get: function () { return staff_1.StaffContext; } });
var staffcomment_1 = require("./staffcomment");
Object.defineProperty(exports, "StaffcommentProvider", { enumerable: true, get: function () { return staffcomment_1.StaffcommentProvider; } });
Object.defineProperty(exports, "StaffcommentContext", { enumerable: true, get: function () { return staffcomment_1.StaffcommentContext; } });
var stafffunctions_1 = require("./stafffunctions");
Object.defineProperty(exports, "StafffunctionsProvider", { enumerable: true, get: function () { return stafffunctions_1.StafffunctionsProvider; } });
Object.defineProperty(exports, "StafffunctionsContext", { enumerable: true, get: function () { return stafffunctions_1.StafffunctionsContext; } });
var stafflog_1 = require("./stafflog");
Object.defineProperty(exports, "StafflogProvider", { enumerable: true, get: function () { return stafflog_1.StafflogProvider; } });
Object.defineProperty(exports, "StafflogContext", { enumerable: true, get: function () { return stafflog_1.StafflogContext; } });
var staffstage_1 = require("./staffstage");
Object.defineProperty(exports, "StaffstageProvider", { enumerable: true, get: function () { return staffstage_1.StaffstageProvider; } });
Object.defineProperty(exports, "StaffstageContext", { enumerable: true, get: function () { return staffstage_1.StaffstageContext; } });
var user_1 = require("./user");
Object.defineProperty(exports, "UserProvider", { enumerable: true, get: function () { return user_1.UserProvider; } });
Object.defineProperty(exports, "UserContext", { enumerable: true, get: function () { return user_1.UserContext; } });
//# sourceMappingURL=index.js.map