"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.newsletter_create = exports.newsletter_list = exports.function_delete = exports.function_partial_update = exports.function_update = exports.function_read = exports.function_create = exports.function_list = exports.expertiseprofile_delete = exports.expertiseprofile_partial_update = exports.expertiseprofile_update = exports.expertiseprofile_read = exports.expertiseprofile_create = exports.expertiseprofile_list = exports.expertise_delete = exports.expertise_partial_update = exports.expertise_update = exports.expertise_read = exports.expertise_create = exports.expertise_list = exports.department_delete = exports.department_partial_update = exports.department_update = exports.department_read = exports.department_create = exports.department_list = exports.condition_delete = exports.condition_partial_update = exports.condition_update = exports.condition_read = exports.condition_create = exports.condition_list = exports.comment_delete = exports.comment_partial_update = exports.comment_update = exports.comment_read = exports.comment_create = exports.comment_list = exports.app_delete = exports.app_partial_update = exports.app_update = exports.app_read = exports.app_create = exports.app_list = exports.address_delete = exports.address_partial_update = exports.address_update = exports.address_read = exports.address_create = exports.address_list = void 0;
exports.staffcomment_update = exports.staffcomment_read = exports.staffcomment_create = exports.staffcomment_list = exports.staff_delete = exports.staff_partial_update = exports.staff_update = exports.staff_read = exports.staff_create = exports.staff_list = exports.role_delete = exports.role_partial_update = exports.role_update = exports.role_read = exports.role_create = exports.role_list = exports.phone_delete = exports.phone_partial_update = exports.phone_update = exports.phone_read = exports.phone_create = exports.phone_list = exports.personstage_delete = exports.personstage_partial_update = exports.personstage_update = exports.personstage_read = exports.personstage_create = exports.personstage_list = exports.personlog_delete = exports.personlog_partial_update = exports.personlog_update = exports.personlog_read = exports.personlog_create = exports.personlog_list = exports.person_delete = exports.person_partial_update = exports.person_update = exports.person_read = exports.person_create = exports.person_list = exports.newsrelatedlink_delete = exports.newsrelatedlink_partial_update = exports.newsrelatedlink_update = exports.newsrelatedlink_read = exports.newsrelatedlink_create = exports.newsrelatedlink_list = exports.newsletter_delete = exports.newsletter_partial_update = exports.newsletter_update = exports.newsletter_read = void 0;
exports.user_delete = exports.user_partial_update = exports.user_update = exports.user_read = exports.user_create = exports.user_list = exports.staffstage_delete = exports.staffstage_partial_update = exports.staffstage_update = exports.staffstage_read = exports.staffstage_create = exports.staffstage_list = exports.stafflog_delete = exports.stafflog_partial_update = exports.stafflog_update = exports.stafflog_read = exports.stafflog_create = exports.stafflog_list = exports.stafffunctions_delete = exports.stafffunctions_partial_update = exports.stafffunctions_update = exports.stafffunctions_read = exports.stafffunctions_create = exports.stafffunctions_list = exports.staffcomment_delete = exports.staffcomment_partial_update = void 0;
var address_1 = require("./address");
Object.defineProperty(exports, "address_list", { enumerable: true, get: function () { return address_1.address_list; } });
Object.defineProperty(exports, "address_create", { enumerable: true, get: function () { return address_1.address_create; } });
Object.defineProperty(exports, "address_read", { enumerable: true, get: function () { return address_1.address_read; } });
Object.defineProperty(exports, "address_update", { enumerable: true, get: function () { return address_1.address_update; } });
Object.defineProperty(exports, "address_partial_update", { enumerable: true, get: function () { return address_1.address_partial_update; } });
Object.defineProperty(exports, "address_delete", { enumerable: true, get: function () { return address_1.address_delete; } });
var app_1 = require("./app");
Object.defineProperty(exports, "app_list", { enumerable: true, get: function () { return app_1.app_list; } });
Object.defineProperty(exports, "app_create", { enumerable: true, get: function () { return app_1.app_create; } });
Object.defineProperty(exports, "app_read", { enumerable: true, get: function () { return app_1.app_read; } });
Object.defineProperty(exports, "app_update", { enumerable: true, get: function () { return app_1.app_update; } });
Object.defineProperty(exports, "app_partial_update", { enumerable: true, get: function () { return app_1.app_partial_update; } });
Object.defineProperty(exports, "app_delete", { enumerable: true, get: function () { return app_1.app_delete; } });
var comment_1 = require("./comment");
Object.defineProperty(exports, "comment_list", { enumerable: true, get: function () { return comment_1.comment_list; } });
Object.defineProperty(exports, "comment_create", { enumerable: true, get: function () { return comment_1.comment_create; } });
Object.defineProperty(exports, "comment_read", { enumerable: true, get: function () { return comment_1.comment_read; } });
Object.defineProperty(exports, "comment_update", { enumerable: true, get: function () { return comment_1.comment_update; } });
Object.defineProperty(exports, "comment_partial_update", { enumerable: true, get: function () { return comment_1.comment_partial_update; } });
Object.defineProperty(exports, "comment_delete", { enumerable: true, get: function () { return comment_1.comment_delete; } });
var condition_1 = require("./condition");
Object.defineProperty(exports, "condition_list", { enumerable: true, get: function () { return condition_1.condition_list; } });
Object.defineProperty(exports, "condition_create", { enumerable: true, get: function () { return condition_1.condition_create; } });
Object.defineProperty(exports, "condition_read", { enumerable: true, get: function () { return condition_1.condition_read; } });
Object.defineProperty(exports, "condition_update", { enumerable: true, get: function () { return condition_1.condition_update; } });
Object.defineProperty(exports, "condition_partial_update", { enumerable: true, get: function () { return condition_1.condition_partial_update; } });
Object.defineProperty(exports, "condition_delete", { enumerable: true, get: function () { return condition_1.condition_delete; } });
var department_1 = require("./department");
Object.defineProperty(exports, "department_list", { enumerable: true, get: function () { return department_1.department_list; } });
Object.defineProperty(exports, "department_create", { enumerable: true, get: function () { return department_1.department_create; } });
Object.defineProperty(exports, "department_read", { enumerable: true, get: function () { return department_1.department_read; } });
Object.defineProperty(exports, "department_update", { enumerable: true, get: function () { return department_1.department_update; } });
Object.defineProperty(exports, "department_partial_update", { enumerable: true, get: function () { return department_1.department_partial_update; } });
Object.defineProperty(exports, "department_delete", { enumerable: true, get: function () { return department_1.department_delete; } });
var expertise_1 = require("./expertise");
Object.defineProperty(exports, "expertise_list", { enumerable: true, get: function () { return expertise_1.expertise_list; } });
Object.defineProperty(exports, "expertise_create", { enumerable: true, get: function () { return expertise_1.expertise_create; } });
Object.defineProperty(exports, "expertise_read", { enumerable: true, get: function () { return expertise_1.expertise_read; } });
Object.defineProperty(exports, "expertise_update", { enumerable: true, get: function () { return expertise_1.expertise_update; } });
Object.defineProperty(exports, "expertise_partial_update", { enumerable: true, get: function () { return expertise_1.expertise_partial_update; } });
Object.defineProperty(exports, "expertise_delete", { enumerable: true, get: function () { return expertise_1.expertise_delete; } });
var expertiseprofile_1 = require("./expertiseprofile");
Object.defineProperty(exports, "expertiseprofile_list", { enumerable: true, get: function () { return expertiseprofile_1.expertiseprofile_list; } });
Object.defineProperty(exports, "expertiseprofile_create", { enumerable: true, get: function () { return expertiseprofile_1.expertiseprofile_create; } });
Object.defineProperty(exports, "expertiseprofile_read", { enumerable: true, get: function () { return expertiseprofile_1.expertiseprofile_read; } });
Object.defineProperty(exports, "expertiseprofile_update", { enumerable: true, get: function () { return expertiseprofile_1.expertiseprofile_update; } });
Object.defineProperty(exports, "expertiseprofile_partial_update", { enumerable: true, get: function () { return expertiseprofile_1.expertiseprofile_partial_update; } });
Object.defineProperty(exports, "expertiseprofile_delete", { enumerable: true, get: function () { return expertiseprofile_1.expertiseprofile_delete; } });
var function_1 = require("./function");
Object.defineProperty(exports, "function_list", { enumerable: true, get: function () { return function_1.function_list; } });
Object.defineProperty(exports, "function_create", { enumerable: true, get: function () { return function_1.function_create; } });
Object.defineProperty(exports, "function_read", { enumerable: true, get: function () { return function_1.function_read; } });
Object.defineProperty(exports, "function_update", { enumerable: true, get: function () { return function_1.function_update; } });
Object.defineProperty(exports, "function_partial_update", { enumerable: true, get: function () { return function_1.function_partial_update; } });
Object.defineProperty(exports, "function_delete", { enumerable: true, get: function () { return function_1.function_delete; } });
var newsletter_1 = require("./newsletter");
Object.defineProperty(exports, "newsletter_list", { enumerable: true, get: function () { return newsletter_1.newsletter_list; } });
Object.defineProperty(exports, "newsletter_create", { enumerable: true, get: function () { return newsletter_1.newsletter_create; } });
Object.defineProperty(exports, "newsletter_read", { enumerable: true, get: function () { return newsletter_1.newsletter_read; } });
Object.defineProperty(exports, "newsletter_update", { enumerable: true, get: function () { return newsletter_1.newsletter_update; } });
Object.defineProperty(exports, "newsletter_partial_update", { enumerable: true, get: function () { return newsletter_1.newsletter_partial_update; } });
Object.defineProperty(exports, "newsletter_delete", { enumerable: true, get: function () { return newsletter_1.newsletter_delete; } });
var newsrelatedlink_1 = require("./newsrelatedlink");
Object.defineProperty(exports, "newsrelatedlink_list", { enumerable: true, get: function () { return newsrelatedlink_1.newsrelatedlink_list; } });
Object.defineProperty(exports, "newsrelatedlink_create", { enumerable: true, get: function () { return newsrelatedlink_1.newsrelatedlink_create; } });
Object.defineProperty(exports, "newsrelatedlink_read", { enumerable: true, get: function () { return newsrelatedlink_1.newsrelatedlink_read; } });
Object.defineProperty(exports, "newsrelatedlink_update", { enumerable: true, get: function () { return newsrelatedlink_1.newsrelatedlink_update; } });
Object.defineProperty(exports, "newsrelatedlink_partial_update", { enumerable: true, get: function () { return newsrelatedlink_1.newsrelatedlink_partial_update; } });
Object.defineProperty(exports, "newsrelatedlink_delete", { enumerable: true, get: function () { return newsrelatedlink_1.newsrelatedlink_delete; } });
var person_1 = require("./person");
Object.defineProperty(exports, "person_list", { enumerable: true, get: function () { return person_1.person_list; } });
Object.defineProperty(exports, "person_create", { enumerable: true, get: function () { return person_1.person_create; } });
Object.defineProperty(exports, "person_read", { enumerable: true, get: function () { return person_1.person_read; } });
Object.defineProperty(exports, "person_update", { enumerable: true, get: function () { return person_1.person_update; } });
Object.defineProperty(exports, "person_partial_update", { enumerable: true, get: function () { return person_1.person_partial_update; } });
Object.defineProperty(exports, "person_delete", { enumerable: true, get: function () { return person_1.person_delete; } });
var personlog_1 = require("./personlog");
Object.defineProperty(exports, "personlog_list", { enumerable: true, get: function () { return personlog_1.personlog_list; } });
Object.defineProperty(exports, "personlog_create", { enumerable: true, get: function () { return personlog_1.personlog_create; } });
Object.defineProperty(exports, "personlog_read", { enumerable: true, get: function () { return personlog_1.personlog_read; } });
Object.defineProperty(exports, "personlog_update", { enumerable: true, get: function () { return personlog_1.personlog_update; } });
Object.defineProperty(exports, "personlog_partial_update", { enumerable: true, get: function () { return personlog_1.personlog_partial_update; } });
Object.defineProperty(exports, "personlog_delete", { enumerable: true, get: function () { return personlog_1.personlog_delete; } });
var personstage_1 = require("./personstage");
Object.defineProperty(exports, "personstage_list", { enumerable: true, get: function () { return personstage_1.personstage_list; } });
Object.defineProperty(exports, "personstage_create", { enumerable: true, get: function () { return personstage_1.personstage_create; } });
Object.defineProperty(exports, "personstage_read", { enumerable: true, get: function () { return personstage_1.personstage_read; } });
Object.defineProperty(exports, "personstage_update", { enumerable: true, get: function () { return personstage_1.personstage_update; } });
Object.defineProperty(exports, "personstage_partial_update", { enumerable: true, get: function () { return personstage_1.personstage_partial_update; } });
Object.defineProperty(exports, "personstage_delete", { enumerable: true, get: function () { return personstage_1.personstage_delete; } });
var phone_1 = require("./phone");
Object.defineProperty(exports, "phone_list", { enumerable: true, get: function () { return phone_1.phone_list; } });
Object.defineProperty(exports, "phone_create", { enumerable: true, get: function () { return phone_1.phone_create; } });
Object.defineProperty(exports, "phone_read", { enumerable: true, get: function () { return phone_1.phone_read; } });
Object.defineProperty(exports, "phone_update", { enumerable: true, get: function () { return phone_1.phone_update; } });
Object.defineProperty(exports, "phone_partial_update", { enumerable: true, get: function () { return phone_1.phone_partial_update; } });
Object.defineProperty(exports, "phone_delete", { enumerable: true, get: function () { return phone_1.phone_delete; } });
var role_1 = require("./role");
Object.defineProperty(exports, "role_list", { enumerable: true, get: function () { return role_1.role_list; } });
Object.defineProperty(exports, "role_create", { enumerable: true, get: function () { return role_1.role_create; } });
Object.defineProperty(exports, "role_read", { enumerable: true, get: function () { return role_1.role_read; } });
Object.defineProperty(exports, "role_update", { enumerable: true, get: function () { return role_1.role_update; } });
Object.defineProperty(exports, "role_partial_update", { enumerable: true, get: function () { return role_1.role_partial_update; } });
Object.defineProperty(exports, "role_delete", { enumerable: true, get: function () { return role_1.role_delete; } });
var staff_1 = require("./staff");
Object.defineProperty(exports, "staff_list", { enumerable: true, get: function () { return staff_1.staff_list; } });
Object.defineProperty(exports, "staff_create", { enumerable: true, get: function () { return staff_1.staff_create; } });
Object.defineProperty(exports, "staff_read", { enumerable: true, get: function () { return staff_1.staff_read; } });
Object.defineProperty(exports, "staff_update", { enumerable: true, get: function () { return staff_1.staff_update; } });
Object.defineProperty(exports, "staff_partial_update", { enumerable: true, get: function () { return staff_1.staff_partial_update; } });
Object.defineProperty(exports, "staff_delete", { enumerable: true, get: function () { return staff_1.staff_delete; } });
var staffcomment_1 = require("./staffcomment");
Object.defineProperty(exports, "staffcomment_list", { enumerable: true, get: function () { return staffcomment_1.staffcomment_list; } });
Object.defineProperty(exports, "staffcomment_create", { enumerable: true, get: function () { return staffcomment_1.staffcomment_create; } });
Object.defineProperty(exports, "staffcomment_read", { enumerable: true, get: function () { return staffcomment_1.staffcomment_read; } });
Object.defineProperty(exports, "staffcomment_update", { enumerable: true, get: function () { return staffcomment_1.staffcomment_update; } });
Object.defineProperty(exports, "staffcomment_partial_update", { enumerable: true, get: function () { return staffcomment_1.staffcomment_partial_update; } });
Object.defineProperty(exports, "staffcomment_delete", { enumerable: true, get: function () { return staffcomment_1.staffcomment_delete; } });
var stafffunctions_1 = require("./stafffunctions");
Object.defineProperty(exports, "stafffunctions_list", { enumerable: true, get: function () { return stafffunctions_1.stafffunctions_list; } });
Object.defineProperty(exports, "stafffunctions_create", { enumerable: true, get: function () { return stafffunctions_1.stafffunctions_create; } });
Object.defineProperty(exports, "stafffunctions_read", { enumerable: true, get: function () { return stafffunctions_1.stafffunctions_read; } });
Object.defineProperty(exports, "stafffunctions_update", { enumerable: true, get: function () { return stafffunctions_1.stafffunctions_update; } });
Object.defineProperty(exports, "stafffunctions_partial_update", { enumerable: true, get: function () { return stafffunctions_1.stafffunctions_partial_update; } });
Object.defineProperty(exports, "stafffunctions_delete", { enumerable: true, get: function () { return stafffunctions_1.stafffunctions_delete; } });
var stafflog_1 = require("./stafflog");
Object.defineProperty(exports, "stafflog_list", { enumerable: true, get: function () { return stafflog_1.stafflog_list; } });
Object.defineProperty(exports, "stafflog_create", { enumerable: true, get: function () { return stafflog_1.stafflog_create; } });
Object.defineProperty(exports, "stafflog_read", { enumerable: true, get: function () { return stafflog_1.stafflog_read; } });
Object.defineProperty(exports, "stafflog_update", { enumerable: true, get: function () { return stafflog_1.stafflog_update; } });
Object.defineProperty(exports, "stafflog_partial_update", { enumerable: true, get: function () { return stafflog_1.stafflog_partial_update; } });
Object.defineProperty(exports, "stafflog_delete", { enumerable: true, get: function () { return stafflog_1.stafflog_delete; } });
var staffstage_1 = require("./staffstage");
Object.defineProperty(exports, "staffstage_list", { enumerable: true, get: function () { return staffstage_1.staffstage_list; } });
Object.defineProperty(exports, "staffstage_create", { enumerable: true, get: function () { return staffstage_1.staffstage_create; } });
Object.defineProperty(exports, "staffstage_read", { enumerable: true, get: function () { return staffstage_1.staffstage_read; } });
Object.defineProperty(exports, "staffstage_update", { enumerable: true, get: function () { return staffstage_1.staffstage_update; } });
Object.defineProperty(exports, "staffstage_partial_update", { enumerable: true, get: function () { return staffstage_1.staffstage_partial_update; } });
Object.defineProperty(exports, "staffstage_delete", { enumerable: true, get: function () { return staffstage_1.staffstage_delete; } });
var user_1 = require("./user");
Object.defineProperty(exports, "user_list", { enumerable: true, get: function () { return user_1.user_list; } });
Object.defineProperty(exports, "user_create", { enumerable: true, get: function () { return user_1.user_create; } });
Object.defineProperty(exports, "user_read", { enumerable: true, get: function () { return user_1.user_read; } });
Object.defineProperty(exports, "user_update", { enumerable: true, get: function () { return user_1.user_update; } });
Object.defineProperty(exports, "user_partial_update", { enumerable: true, get: function () { return user_1.user_partial_update; } });
Object.defineProperty(exports, "user_delete", { enumerable: true, get: function () { return user_1.user_delete; } });
//# sourceMappingURL=index.js.map