"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.condition_delete = exports.condition_partial_updateFields = exports.condition_partial_update = exports.condition_updateFields = exports.condition_update = exports.condition_read = exports.condition_createFields = exports.condition_create = exports.condition_listFields = exports.condition_list = exports.comment_delete = exports.comment_partial_updateFields = exports.comment_partial_update = exports.comment_updateFields = exports.comment_update = exports.comment_read = exports.comment_createFields = exports.comment_create = exports.comment_listFields = exports.comment_list = exports.app_delete = exports.app_partial_updateFields = exports.app_partial_update = exports.app_updateFields = exports.app_update = exports.app_read = exports.app_createFields = exports.app_create = exports.app_listFields = exports.app_list = exports.answers_delete = exports.answers_partial_updateFields = exports.answers_partial_update = exports.answers_updateFields = exports.answers_update = exports.answers_read = exports.answers_createFields = exports.answers_create = exports.answers_listFields = exports.answers_list = exports.address_delete = exports.address_partial_updateFields = exports.address_partial_update = exports.address_updateFields = exports.address_update = exports.address_read = exports.address_createFields = exports.address_create = exports.address_listFields = exports.address_list = void 0;
exports.newsletter_delete = exports.newsletter_partial_updateFields = exports.newsletter_partial_update = exports.newsletter_updateFields = exports.newsletter_update = exports.newsletter_read = exports.newsletter_createFields = exports.newsletter_create = exports.newsletter_listFields = exports.newsletter_list = exports.function_delete = exports.function_partial_updateFields = exports.function_partial_update = exports.function_updateFields = exports.function_update = exports.function_read = exports.function_createFields = exports.function_create = exports.function_listFields = exports.function_list = exports.expertiseprofile_delete = exports.expertiseprofile_partial_updateFields = exports.expertiseprofile_partial_update = exports.expertiseprofile_updateFields = exports.expertiseprofile_update = exports.expertiseprofile_read = exports.expertiseprofile_createFields = exports.expertiseprofile_create = exports.expertiseprofile_listFields = exports.expertiseprofile_list = exports.expertise_delete = exports.expertise_partial_updateFields = exports.expertise_partial_update = exports.expertise_updateFields = exports.expertise_update = exports.expertise_read = exports.expertise_createFields = exports.expertise_create = exports.expertise_listFields = exports.expertise_list = exports.department_delete = exports.department_partial_updateFields = exports.department_partial_update = exports.department_updateFields = exports.department_update = exports.department_read = exports.department_createFields = exports.department_create = exports.department_listFields = exports.department_list = void 0;
exports.phone_delete = exports.phone_partial_updateFields = exports.phone_partial_update = exports.phone_updateFields = exports.phone_update = exports.phone_read = exports.phone_createFields = exports.phone_create = exports.phone_listFields = exports.phone_list = exports.personstage_delete = exports.personstage_partial_updateFields = exports.personstage_partial_update = exports.personstage_updateFields = exports.personstage_update = exports.personstage_read = exports.personstage_createFields = exports.personstage_create = exports.personstage_listFields = exports.personstage_list = exports.personlog_delete = exports.personlog_partial_updateFields = exports.personlog_partial_update = exports.personlog_updateFields = exports.personlog_update = exports.personlog_read = exports.personlog_createFields = exports.personlog_create = exports.personlog_listFields = exports.personlog_list = exports.person_delete = exports.person_partial_updateFields = exports.person_partial_update = exports.person_updateFields = exports.person_update = exports.person_read = exports.person_createFields = exports.person_create = exports.person_listFields = exports.person_list = exports.newsrelatedlink_delete = exports.newsrelatedlink_partial_updateFields = exports.newsrelatedlink_partial_update = exports.newsrelatedlink_updateFields = exports.newsrelatedlink_update = exports.newsrelatedlink_read = exports.newsrelatedlink_createFields = exports.newsrelatedlink_create = exports.newsrelatedlink_listFields = exports.newsrelatedlink_list = void 0;
exports.staffcomment_delete = exports.staffcomment_partial_updateFields = exports.staffcomment_partial_update = exports.staffcomment_updateFields = exports.staffcomment_update = exports.staffcomment_read = exports.staffcomment_createFields = exports.staffcomment_create = exports.staffcomment_listFields = exports.staffcomment_list = exports.staff_delete = exports.staff_partial_updateFields = exports.staff_partial_update = exports.staff_updateFields = exports.staff_update = exports.staff_read = exports.staff_createFields = exports.staff_create = exports.staff_listFields = exports.staff_list = exports.role_delete = exports.role_partial_updateFields = exports.role_partial_update = exports.role_updateFields = exports.role_update = exports.role_read = exports.role_createFields = exports.role_create = exports.role_listFields = exports.role_list = exports.questionsrelatedlink_delete = exports.questionsrelatedlink_partial_updateFields = exports.questionsrelatedlink_partial_update = exports.questionsrelatedlink_updateFields = exports.questionsrelatedlink_update = exports.questionsrelatedlink_read = exports.questionsrelatedlink_createFields = exports.questionsrelatedlink_create = exports.questionsrelatedlink_listFields = exports.questionsrelatedlink_list = exports.question_delete = exports.question_partial_updateFields = exports.question_partial_update = exports.question_updateFields = exports.question_update = exports.question_read = exports.question_createFields = exports.question_create = exports.question_listFields = exports.question_list = void 0;
exports.user_delete = exports.user_partial_updateFields = exports.user_partial_update = exports.user_updateFields = exports.user_update = exports.user_read = exports.user_createFields = exports.user_create = exports.user_listFields = exports.user_list = exports.staffstage_delete = exports.staffstage_partial_updateFields = exports.staffstage_partial_update = exports.staffstage_updateFields = exports.staffstage_update = exports.staffstage_read = exports.staffstage_createFields = exports.staffstage_create = exports.staffstage_listFields = exports.staffstage_list = exports.stafflog_delete = exports.stafflog_partial_updateFields = exports.stafflog_partial_update = exports.stafflog_updateFields = exports.stafflog_update = exports.stafflog_read = exports.stafflog_createFields = exports.stafflog_create = exports.stafflog_listFields = exports.stafflog_list = exports.stafffunctions_delete = exports.stafffunctions_partial_updateFields = exports.stafffunctions_partial_update = exports.stafffunctions_updateFields = exports.stafffunctions_update = exports.stafffunctions_read = exports.stafffunctions_createFields = exports.stafffunctions_create = exports.stafffunctions_listFields = exports.stafffunctions_list = void 0;
var address_1 = require("./address");
Object.defineProperty(exports, "address_list", { enumerable: true, get: function () { return address_1.address_list; } });
Object.defineProperty(exports, "address_listFields", { enumerable: true, get: function () { return address_1.address_listFields; } });
Object.defineProperty(exports, "address_create", { enumerable: true, get: function () { return address_1.address_create; } });
Object.defineProperty(exports, "address_createFields", { enumerable: true, get: function () { return address_1.address_createFields; } });
Object.defineProperty(exports, "address_read", { enumerable: true, get: function () { return address_1.address_read; } });
Object.defineProperty(exports, "address_update", { enumerable: true, get: function () { return address_1.address_update; } });
Object.defineProperty(exports, "address_updateFields", { enumerable: true, get: function () { return address_1.address_updateFields; } });
Object.defineProperty(exports, "address_partial_update", { enumerable: true, get: function () { return address_1.address_partial_update; } });
Object.defineProperty(exports, "address_partial_updateFields", { enumerable: true, get: function () { return address_1.address_partial_updateFields; } });
Object.defineProperty(exports, "address_delete", { enumerable: true, get: function () { return address_1.address_delete; } });
var answers_1 = require("./answers");
Object.defineProperty(exports, "answers_list", { enumerable: true, get: function () { return answers_1.answers_list; } });
Object.defineProperty(exports, "answers_listFields", { enumerable: true, get: function () { return answers_1.answers_listFields; } });
Object.defineProperty(exports, "answers_create", { enumerable: true, get: function () { return answers_1.answers_create; } });
Object.defineProperty(exports, "answers_createFields", { enumerable: true, get: function () { return answers_1.answers_createFields; } });
Object.defineProperty(exports, "answers_read", { enumerable: true, get: function () { return answers_1.answers_read; } });
Object.defineProperty(exports, "answers_update", { enumerable: true, get: function () { return answers_1.answers_update; } });
Object.defineProperty(exports, "answers_updateFields", { enumerable: true, get: function () { return answers_1.answers_updateFields; } });
Object.defineProperty(exports, "answers_partial_update", { enumerable: true, get: function () { return answers_1.answers_partial_update; } });
Object.defineProperty(exports, "answers_partial_updateFields", { enumerable: true, get: function () { return answers_1.answers_partial_updateFields; } });
Object.defineProperty(exports, "answers_delete", { enumerable: true, get: function () { return answers_1.answers_delete; } });
var app_1 = require("./app");
Object.defineProperty(exports, "app_list", { enumerable: true, get: function () { return app_1.app_list; } });
Object.defineProperty(exports, "app_listFields", { enumerable: true, get: function () { return app_1.app_listFields; } });
Object.defineProperty(exports, "app_create", { enumerable: true, get: function () { return app_1.app_create; } });
Object.defineProperty(exports, "app_createFields", { enumerable: true, get: function () { return app_1.app_createFields; } });
Object.defineProperty(exports, "app_read", { enumerable: true, get: function () { return app_1.app_read; } });
Object.defineProperty(exports, "app_update", { enumerable: true, get: function () { return app_1.app_update; } });
Object.defineProperty(exports, "app_updateFields", { enumerable: true, get: function () { return app_1.app_updateFields; } });
Object.defineProperty(exports, "app_partial_update", { enumerable: true, get: function () { return app_1.app_partial_update; } });
Object.defineProperty(exports, "app_partial_updateFields", { enumerable: true, get: function () { return app_1.app_partial_updateFields; } });
Object.defineProperty(exports, "app_delete", { enumerable: true, get: function () { return app_1.app_delete; } });
var comment_1 = require("./comment");
Object.defineProperty(exports, "comment_list", { enumerable: true, get: function () { return comment_1.comment_list; } });
Object.defineProperty(exports, "comment_listFields", { enumerable: true, get: function () { return comment_1.comment_listFields; } });
Object.defineProperty(exports, "comment_create", { enumerable: true, get: function () { return comment_1.comment_create; } });
Object.defineProperty(exports, "comment_createFields", { enumerable: true, get: function () { return comment_1.comment_createFields; } });
Object.defineProperty(exports, "comment_read", { enumerable: true, get: function () { return comment_1.comment_read; } });
Object.defineProperty(exports, "comment_update", { enumerable: true, get: function () { return comment_1.comment_update; } });
Object.defineProperty(exports, "comment_updateFields", { enumerable: true, get: function () { return comment_1.comment_updateFields; } });
Object.defineProperty(exports, "comment_partial_update", { enumerable: true, get: function () { return comment_1.comment_partial_update; } });
Object.defineProperty(exports, "comment_partial_updateFields", { enumerable: true, get: function () { return comment_1.comment_partial_updateFields; } });
Object.defineProperty(exports, "comment_delete", { enumerable: true, get: function () { return comment_1.comment_delete; } });
var condition_1 = require("./condition");
Object.defineProperty(exports, "condition_list", { enumerable: true, get: function () { return condition_1.condition_list; } });
Object.defineProperty(exports, "condition_listFields", { enumerable: true, get: function () { return condition_1.condition_listFields; } });
Object.defineProperty(exports, "condition_create", { enumerable: true, get: function () { return condition_1.condition_create; } });
Object.defineProperty(exports, "condition_createFields", { enumerable: true, get: function () { return condition_1.condition_createFields; } });
Object.defineProperty(exports, "condition_read", { enumerable: true, get: function () { return condition_1.condition_read; } });
Object.defineProperty(exports, "condition_update", { enumerable: true, get: function () { return condition_1.condition_update; } });
Object.defineProperty(exports, "condition_updateFields", { enumerable: true, get: function () { return condition_1.condition_updateFields; } });
Object.defineProperty(exports, "condition_partial_update", { enumerable: true, get: function () { return condition_1.condition_partial_update; } });
Object.defineProperty(exports, "condition_partial_updateFields", { enumerable: true, get: function () { return condition_1.condition_partial_updateFields; } });
Object.defineProperty(exports, "condition_delete", { enumerable: true, get: function () { return condition_1.condition_delete; } });
var department_1 = require("./department");
Object.defineProperty(exports, "department_list", { enumerable: true, get: function () { return department_1.department_list; } });
Object.defineProperty(exports, "department_listFields", { enumerable: true, get: function () { return department_1.department_listFields; } });
Object.defineProperty(exports, "department_create", { enumerable: true, get: function () { return department_1.department_create; } });
Object.defineProperty(exports, "department_createFields", { enumerable: true, get: function () { return department_1.department_createFields; } });
Object.defineProperty(exports, "department_read", { enumerable: true, get: function () { return department_1.department_read; } });
Object.defineProperty(exports, "department_update", { enumerable: true, get: function () { return department_1.department_update; } });
Object.defineProperty(exports, "department_updateFields", { enumerable: true, get: function () { return department_1.department_updateFields; } });
Object.defineProperty(exports, "department_partial_update", { enumerable: true, get: function () { return department_1.department_partial_update; } });
Object.defineProperty(exports, "department_partial_updateFields", { enumerable: true, get: function () { return department_1.department_partial_updateFields; } });
Object.defineProperty(exports, "department_delete", { enumerable: true, get: function () { return department_1.department_delete; } });
var expertise_1 = require("./expertise");
Object.defineProperty(exports, "expertise_list", { enumerable: true, get: function () { return expertise_1.expertise_list; } });
Object.defineProperty(exports, "expertise_listFields", { enumerable: true, get: function () { return expertise_1.expertise_listFields; } });
Object.defineProperty(exports, "expertise_create", { enumerable: true, get: function () { return expertise_1.expertise_create; } });
Object.defineProperty(exports, "expertise_createFields", { enumerable: true, get: function () { return expertise_1.expertise_createFields; } });
Object.defineProperty(exports, "expertise_read", { enumerable: true, get: function () { return expertise_1.expertise_read; } });
Object.defineProperty(exports, "expertise_update", { enumerable: true, get: function () { return expertise_1.expertise_update; } });
Object.defineProperty(exports, "expertise_updateFields", { enumerable: true, get: function () { return expertise_1.expertise_updateFields; } });
Object.defineProperty(exports, "expertise_partial_update", { enumerable: true, get: function () { return expertise_1.expertise_partial_update; } });
Object.defineProperty(exports, "expertise_partial_updateFields", { enumerable: true, get: function () { return expertise_1.expertise_partial_updateFields; } });
Object.defineProperty(exports, "expertise_delete", { enumerable: true, get: function () { return expertise_1.expertise_delete; } });
var expertiseprofile_1 = require("./expertiseprofile");
Object.defineProperty(exports, "expertiseprofile_list", { enumerable: true, get: function () { return expertiseprofile_1.expertiseprofile_list; } });
Object.defineProperty(exports, "expertiseprofile_listFields", { enumerable: true, get: function () { return expertiseprofile_1.expertiseprofile_listFields; } });
Object.defineProperty(exports, "expertiseprofile_create", { enumerable: true, get: function () { return expertiseprofile_1.expertiseprofile_create; } });
Object.defineProperty(exports, "expertiseprofile_createFields", { enumerable: true, get: function () { return expertiseprofile_1.expertiseprofile_createFields; } });
Object.defineProperty(exports, "expertiseprofile_read", { enumerable: true, get: function () { return expertiseprofile_1.expertiseprofile_read; } });
Object.defineProperty(exports, "expertiseprofile_update", { enumerable: true, get: function () { return expertiseprofile_1.expertiseprofile_update; } });
Object.defineProperty(exports, "expertiseprofile_updateFields", { enumerable: true, get: function () { return expertiseprofile_1.expertiseprofile_updateFields; } });
Object.defineProperty(exports, "expertiseprofile_partial_update", { enumerable: true, get: function () { return expertiseprofile_1.expertiseprofile_partial_update; } });
Object.defineProperty(exports, "expertiseprofile_partial_updateFields", { enumerable: true, get: function () { return expertiseprofile_1.expertiseprofile_partial_updateFields; } });
Object.defineProperty(exports, "expertiseprofile_delete", { enumerable: true, get: function () { return expertiseprofile_1.expertiseprofile_delete; } });
var function_1 = require("./function");
Object.defineProperty(exports, "function_list", { enumerable: true, get: function () { return function_1.function_list; } });
Object.defineProperty(exports, "function_listFields", { enumerable: true, get: function () { return function_1.function_listFields; } });
Object.defineProperty(exports, "function_create", { enumerable: true, get: function () { return function_1.function_create; } });
Object.defineProperty(exports, "function_createFields", { enumerable: true, get: function () { return function_1.function_createFields; } });
Object.defineProperty(exports, "function_read", { enumerable: true, get: function () { return function_1.function_read; } });
Object.defineProperty(exports, "function_update", { enumerable: true, get: function () { return function_1.function_update; } });
Object.defineProperty(exports, "function_updateFields", { enumerable: true, get: function () { return function_1.function_updateFields; } });
Object.defineProperty(exports, "function_partial_update", { enumerable: true, get: function () { return function_1.function_partial_update; } });
Object.defineProperty(exports, "function_partial_updateFields", { enumerable: true, get: function () { return function_1.function_partial_updateFields; } });
Object.defineProperty(exports, "function_delete", { enumerable: true, get: function () { return function_1.function_delete; } });
var newsletter_1 = require("./newsletter");
Object.defineProperty(exports, "newsletter_list", { enumerable: true, get: function () { return newsletter_1.newsletter_list; } });
Object.defineProperty(exports, "newsletter_listFields", { enumerable: true, get: function () { return newsletter_1.newsletter_listFields; } });
Object.defineProperty(exports, "newsletter_create", { enumerable: true, get: function () { return newsletter_1.newsletter_create; } });
Object.defineProperty(exports, "newsletter_createFields", { enumerable: true, get: function () { return newsletter_1.newsletter_createFields; } });
Object.defineProperty(exports, "newsletter_read", { enumerable: true, get: function () { return newsletter_1.newsletter_read; } });
Object.defineProperty(exports, "newsletter_update", { enumerable: true, get: function () { return newsletter_1.newsletter_update; } });
Object.defineProperty(exports, "newsletter_updateFields", { enumerable: true, get: function () { return newsletter_1.newsletter_updateFields; } });
Object.defineProperty(exports, "newsletter_partial_update", { enumerable: true, get: function () { return newsletter_1.newsletter_partial_update; } });
Object.defineProperty(exports, "newsletter_partial_updateFields", { enumerable: true, get: function () { return newsletter_1.newsletter_partial_updateFields; } });
Object.defineProperty(exports, "newsletter_delete", { enumerable: true, get: function () { return newsletter_1.newsletter_delete; } });
var newsrelatedlink_1 = require("./newsrelatedlink");
Object.defineProperty(exports, "newsrelatedlink_list", { enumerable: true, get: function () { return newsrelatedlink_1.newsrelatedlink_list; } });
Object.defineProperty(exports, "newsrelatedlink_listFields", { enumerable: true, get: function () { return newsrelatedlink_1.newsrelatedlink_listFields; } });
Object.defineProperty(exports, "newsrelatedlink_create", { enumerable: true, get: function () { return newsrelatedlink_1.newsrelatedlink_create; } });
Object.defineProperty(exports, "newsrelatedlink_createFields", { enumerable: true, get: function () { return newsrelatedlink_1.newsrelatedlink_createFields; } });
Object.defineProperty(exports, "newsrelatedlink_read", { enumerable: true, get: function () { return newsrelatedlink_1.newsrelatedlink_read; } });
Object.defineProperty(exports, "newsrelatedlink_update", { enumerable: true, get: function () { return newsrelatedlink_1.newsrelatedlink_update; } });
Object.defineProperty(exports, "newsrelatedlink_updateFields", { enumerable: true, get: function () { return newsrelatedlink_1.newsrelatedlink_updateFields; } });
Object.defineProperty(exports, "newsrelatedlink_partial_update", { enumerable: true, get: function () { return newsrelatedlink_1.newsrelatedlink_partial_update; } });
Object.defineProperty(exports, "newsrelatedlink_partial_updateFields", { enumerable: true, get: function () { return newsrelatedlink_1.newsrelatedlink_partial_updateFields; } });
Object.defineProperty(exports, "newsrelatedlink_delete", { enumerable: true, get: function () { return newsrelatedlink_1.newsrelatedlink_delete; } });
var person_1 = require("./person");
Object.defineProperty(exports, "person_list", { enumerable: true, get: function () { return person_1.person_list; } });
Object.defineProperty(exports, "person_listFields", { enumerable: true, get: function () { return person_1.person_listFields; } });
Object.defineProperty(exports, "person_create", { enumerable: true, get: function () { return person_1.person_create; } });
Object.defineProperty(exports, "person_createFields", { enumerable: true, get: function () { return person_1.person_createFields; } });
Object.defineProperty(exports, "person_read", { enumerable: true, get: function () { return person_1.person_read; } });
Object.defineProperty(exports, "person_update", { enumerable: true, get: function () { return person_1.person_update; } });
Object.defineProperty(exports, "person_updateFields", { enumerable: true, get: function () { return person_1.person_updateFields; } });
Object.defineProperty(exports, "person_partial_update", { enumerable: true, get: function () { return person_1.person_partial_update; } });
Object.defineProperty(exports, "person_partial_updateFields", { enumerable: true, get: function () { return person_1.person_partial_updateFields; } });
Object.defineProperty(exports, "person_delete", { enumerable: true, get: function () { return person_1.person_delete; } });
var personlog_1 = require("./personlog");
Object.defineProperty(exports, "personlog_list", { enumerable: true, get: function () { return personlog_1.personlog_list; } });
Object.defineProperty(exports, "personlog_listFields", { enumerable: true, get: function () { return personlog_1.personlog_listFields; } });
Object.defineProperty(exports, "personlog_create", { enumerable: true, get: function () { return personlog_1.personlog_create; } });
Object.defineProperty(exports, "personlog_createFields", { enumerable: true, get: function () { return personlog_1.personlog_createFields; } });
Object.defineProperty(exports, "personlog_read", { enumerable: true, get: function () { return personlog_1.personlog_read; } });
Object.defineProperty(exports, "personlog_update", { enumerable: true, get: function () { return personlog_1.personlog_update; } });
Object.defineProperty(exports, "personlog_updateFields", { enumerable: true, get: function () { return personlog_1.personlog_updateFields; } });
Object.defineProperty(exports, "personlog_partial_update", { enumerable: true, get: function () { return personlog_1.personlog_partial_update; } });
Object.defineProperty(exports, "personlog_partial_updateFields", { enumerable: true, get: function () { return personlog_1.personlog_partial_updateFields; } });
Object.defineProperty(exports, "personlog_delete", { enumerable: true, get: function () { return personlog_1.personlog_delete; } });
var personstage_1 = require("./personstage");
Object.defineProperty(exports, "personstage_list", { enumerable: true, get: function () { return personstage_1.personstage_list; } });
Object.defineProperty(exports, "personstage_listFields", { enumerable: true, get: function () { return personstage_1.personstage_listFields; } });
Object.defineProperty(exports, "personstage_create", { enumerable: true, get: function () { return personstage_1.personstage_create; } });
Object.defineProperty(exports, "personstage_createFields", { enumerable: true, get: function () { return personstage_1.personstage_createFields; } });
Object.defineProperty(exports, "personstage_read", { enumerable: true, get: function () { return personstage_1.personstage_read; } });
Object.defineProperty(exports, "personstage_update", { enumerable: true, get: function () { return personstage_1.personstage_update; } });
Object.defineProperty(exports, "personstage_updateFields", { enumerable: true, get: function () { return personstage_1.personstage_updateFields; } });
Object.defineProperty(exports, "personstage_partial_update", { enumerable: true, get: function () { return personstage_1.personstage_partial_update; } });
Object.defineProperty(exports, "personstage_partial_updateFields", { enumerable: true, get: function () { return personstage_1.personstage_partial_updateFields; } });
Object.defineProperty(exports, "personstage_delete", { enumerable: true, get: function () { return personstage_1.personstage_delete; } });
var phone_1 = require("./phone");
Object.defineProperty(exports, "phone_list", { enumerable: true, get: function () { return phone_1.phone_list; } });
Object.defineProperty(exports, "phone_listFields", { enumerable: true, get: function () { return phone_1.phone_listFields; } });
Object.defineProperty(exports, "phone_create", { enumerable: true, get: function () { return phone_1.phone_create; } });
Object.defineProperty(exports, "phone_createFields", { enumerable: true, get: function () { return phone_1.phone_createFields; } });
Object.defineProperty(exports, "phone_read", { enumerable: true, get: function () { return phone_1.phone_read; } });
Object.defineProperty(exports, "phone_update", { enumerable: true, get: function () { return phone_1.phone_update; } });
Object.defineProperty(exports, "phone_updateFields", { enumerable: true, get: function () { return phone_1.phone_updateFields; } });
Object.defineProperty(exports, "phone_partial_update", { enumerable: true, get: function () { return phone_1.phone_partial_update; } });
Object.defineProperty(exports, "phone_partial_updateFields", { enumerable: true, get: function () { return phone_1.phone_partial_updateFields; } });
Object.defineProperty(exports, "phone_delete", { enumerable: true, get: function () { return phone_1.phone_delete; } });
var question_1 = require("./question");
Object.defineProperty(exports, "question_list", { enumerable: true, get: function () { return question_1.question_list; } });
Object.defineProperty(exports, "question_listFields", { enumerable: true, get: function () { return question_1.question_listFields; } });
Object.defineProperty(exports, "question_create", { enumerable: true, get: function () { return question_1.question_create; } });
Object.defineProperty(exports, "question_createFields", { enumerable: true, get: function () { return question_1.question_createFields; } });
Object.defineProperty(exports, "question_read", { enumerable: true, get: function () { return question_1.question_read; } });
Object.defineProperty(exports, "question_update", { enumerable: true, get: function () { return question_1.question_update; } });
Object.defineProperty(exports, "question_updateFields", { enumerable: true, get: function () { return question_1.question_updateFields; } });
Object.defineProperty(exports, "question_partial_update", { enumerable: true, get: function () { return question_1.question_partial_update; } });
Object.defineProperty(exports, "question_partial_updateFields", { enumerable: true, get: function () { return question_1.question_partial_updateFields; } });
Object.defineProperty(exports, "question_delete", { enumerable: true, get: function () { return question_1.question_delete; } });
var questionsrelatedlink_1 = require("./questionsrelatedlink");
Object.defineProperty(exports, "questionsrelatedlink_list", { enumerable: true, get: function () { return questionsrelatedlink_1.questionsrelatedlink_list; } });
Object.defineProperty(exports, "questionsrelatedlink_listFields", { enumerable: true, get: function () { return questionsrelatedlink_1.questionsrelatedlink_listFields; } });
Object.defineProperty(exports, "questionsrelatedlink_create", { enumerable: true, get: function () { return questionsrelatedlink_1.questionsrelatedlink_create; } });
Object.defineProperty(exports, "questionsrelatedlink_createFields", { enumerable: true, get: function () { return questionsrelatedlink_1.questionsrelatedlink_createFields; } });
Object.defineProperty(exports, "questionsrelatedlink_read", { enumerable: true, get: function () { return questionsrelatedlink_1.questionsrelatedlink_read; } });
Object.defineProperty(exports, "questionsrelatedlink_update", { enumerable: true, get: function () { return questionsrelatedlink_1.questionsrelatedlink_update; } });
Object.defineProperty(exports, "questionsrelatedlink_updateFields", { enumerable: true, get: function () { return questionsrelatedlink_1.questionsrelatedlink_updateFields; } });
Object.defineProperty(exports, "questionsrelatedlink_partial_update", { enumerable: true, get: function () { return questionsrelatedlink_1.questionsrelatedlink_partial_update; } });
Object.defineProperty(exports, "questionsrelatedlink_partial_updateFields", { enumerable: true, get: function () { return questionsrelatedlink_1.questionsrelatedlink_partial_updateFields; } });
Object.defineProperty(exports, "questionsrelatedlink_delete", { enumerable: true, get: function () { return questionsrelatedlink_1.questionsrelatedlink_delete; } });
var role_1 = require("./role");
Object.defineProperty(exports, "role_list", { enumerable: true, get: function () { return role_1.role_list; } });
Object.defineProperty(exports, "role_listFields", { enumerable: true, get: function () { return role_1.role_listFields; } });
Object.defineProperty(exports, "role_create", { enumerable: true, get: function () { return role_1.role_create; } });
Object.defineProperty(exports, "role_createFields", { enumerable: true, get: function () { return role_1.role_createFields; } });
Object.defineProperty(exports, "role_read", { enumerable: true, get: function () { return role_1.role_read; } });
Object.defineProperty(exports, "role_update", { enumerable: true, get: function () { return role_1.role_update; } });
Object.defineProperty(exports, "role_updateFields", { enumerable: true, get: function () { return role_1.role_updateFields; } });
Object.defineProperty(exports, "role_partial_update", { enumerable: true, get: function () { return role_1.role_partial_update; } });
Object.defineProperty(exports, "role_partial_updateFields", { enumerable: true, get: function () { return role_1.role_partial_updateFields; } });
Object.defineProperty(exports, "role_delete", { enumerable: true, get: function () { return role_1.role_delete; } });
var staff_1 = require("./staff");
Object.defineProperty(exports, "staff_list", { enumerable: true, get: function () { return staff_1.staff_list; } });
Object.defineProperty(exports, "staff_listFields", { enumerable: true, get: function () { return staff_1.staff_listFields; } });
Object.defineProperty(exports, "staff_create", { enumerable: true, get: function () { return staff_1.staff_create; } });
Object.defineProperty(exports, "staff_createFields", { enumerable: true, get: function () { return staff_1.staff_createFields; } });
Object.defineProperty(exports, "staff_read", { enumerable: true, get: function () { return staff_1.staff_read; } });
Object.defineProperty(exports, "staff_update", { enumerable: true, get: function () { return staff_1.staff_update; } });
Object.defineProperty(exports, "staff_updateFields", { enumerable: true, get: function () { return staff_1.staff_updateFields; } });
Object.defineProperty(exports, "staff_partial_update", { enumerable: true, get: function () { return staff_1.staff_partial_update; } });
Object.defineProperty(exports, "staff_partial_updateFields", { enumerable: true, get: function () { return staff_1.staff_partial_updateFields; } });
Object.defineProperty(exports, "staff_delete", { enumerable: true, get: function () { return staff_1.staff_delete; } });
var staffcomment_1 = require("./staffcomment");
Object.defineProperty(exports, "staffcomment_list", { enumerable: true, get: function () { return staffcomment_1.staffcomment_list; } });
Object.defineProperty(exports, "staffcomment_listFields", { enumerable: true, get: function () { return staffcomment_1.staffcomment_listFields; } });
Object.defineProperty(exports, "staffcomment_create", { enumerable: true, get: function () { return staffcomment_1.staffcomment_create; } });
Object.defineProperty(exports, "staffcomment_createFields", { enumerable: true, get: function () { return staffcomment_1.staffcomment_createFields; } });
Object.defineProperty(exports, "staffcomment_read", { enumerable: true, get: function () { return staffcomment_1.staffcomment_read; } });
Object.defineProperty(exports, "staffcomment_update", { enumerable: true, get: function () { return staffcomment_1.staffcomment_update; } });
Object.defineProperty(exports, "staffcomment_updateFields", { enumerable: true, get: function () { return staffcomment_1.staffcomment_updateFields; } });
Object.defineProperty(exports, "staffcomment_partial_update", { enumerable: true, get: function () { return staffcomment_1.staffcomment_partial_update; } });
Object.defineProperty(exports, "staffcomment_partial_updateFields", { enumerable: true, get: function () { return staffcomment_1.staffcomment_partial_updateFields; } });
Object.defineProperty(exports, "staffcomment_delete", { enumerable: true, get: function () { return staffcomment_1.staffcomment_delete; } });
var stafffunctions_1 = require("./stafffunctions");
Object.defineProperty(exports, "stafffunctions_list", { enumerable: true, get: function () { return stafffunctions_1.stafffunctions_list; } });
Object.defineProperty(exports, "stafffunctions_listFields", { enumerable: true, get: function () { return stafffunctions_1.stafffunctions_listFields; } });
Object.defineProperty(exports, "stafffunctions_create", { enumerable: true, get: function () { return stafffunctions_1.stafffunctions_create; } });
Object.defineProperty(exports, "stafffunctions_createFields", { enumerable: true, get: function () { return stafffunctions_1.stafffunctions_createFields; } });
Object.defineProperty(exports, "stafffunctions_read", { enumerable: true, get: function () { return stafffunctions_1.stafffunctions_read; } });
Object.defineProperty(exports, "stafffunctions_update", { enumerable: true, get: function () { return stafffunctions_1.stafffunctions_update; } });
Object.defineProperty(exports, "stafffunctions_updateFields", { enumerable: true, get: function () { return stafffunctions_1.stafffunctions_updateFields; } });
Object.defineProperty(exports, "stafffunctions_partial_update", { enumerable: true, get: function () { return stafffunctions_1.stafffunctions_partial_update; } });
Object.defineProperty(exports, "stafffunctions_partial_updateFields", { enumerable: true, get: function () { return stafffunctions_1.stafffunctions_partial_updateFields; } });
Object.defineProperty(exports, "stafffunctions_delete", { enumerable: true, get: function () { return stafffunctions_1.stafffunctions_delete; } });
var stafflog_1 = require("./stafflog");
Object.defineProperty(exports, "stafflog_list", { enumerable: true, get: function () { return stafflog_1.stafflog_list; } });
Object.defineProperty(exports, "stafflog_listFields", { enumerable: true, get: function () { return stafflog_1.stafflog_listFields; } });
Object.defineProperty(exports, "stafflog_create", { enumerable: true, get: function () { return stafflog_1.stafflog_create; } });
Object.defineProperty(exports, "stafflog_createFields", { enumerable: true, get: function () { return stafflog_1.stafflog_createFields; } });
Object.defineProperty(exports, "stafflog_read", { enumerable: true, get: function () { return stafflog_1.stafflog_read; } });
Object.defineProperty(exports, "stafflog_update", { enumerable: true, get: function () { return stafflog_1.stafflog_update; } });
Object.defineProperty(exports, "stafflog_updateFields", { enumerable: true, get: function () { return stafflog_1.stafflog_updateFields; } });
Object.defineProperty(exports, "stafflog_partial_update", { enumerable: true, get: function () { return stafflog_1.stafflog_partial_update; } });
Object.defineProperty(exports, "stafflog_partial_updateFields", { enumerable: true, get: function () { return stafflog_1.stafflog_partial_updateFields; } });
Object.defineProperty(exports, "stafflog_delete", { enumerable: true, get: function () { return stafflog_1.stafflog_delete; } });
var staffstage_1 = require("./staffstage");
Object.defineProperty(exports, "staffstage_list", { enumerable: true, get: function () { return staffstage_1.staffstage_list; } });
Object.defineProperty(exports, "staffstage_listFields", { enumerable: true, get: function () { return staffstage_1.staffstage_listFields; } });
Object.defineProperty(exports, "staffstage_create", { enumerable: true, get: function () { return staffstage_1.staffstage_create; } });
Object.defineProperty(exports, "staffstage_createFields", { enumerable: true, get: function () { return staffstage_1.staffstage_createFields; } });
Object.defineProperty(exports, "staffstage_read", { enumerable: true, get: function () { return staffstage_1.staffstage_read; } });
Object.defineProperty(exports, "staffstage_update", { enumerable: true, get: function () { return staffstage_1.staffstage_update; } });
Object.defineProperty(exports, "staffstage_updateFields", { enumerable: true, get: function () { return staffstage_1.staffstage_updateFields; } });
Object.defineProperty(exports, "staffstage_partial_update", { enumerable: true, get: function () { return staffstage_1.staffstage_partial_update; } });
Object.defineProperty(exports, "staffstage_partial_updateFields", { enumerable: true, get: function () { return staffstage_1.staffstage_partial_updateFields; } });
Object.defineProperty(exports, "staffstage_delete", { enumerable: true, get: function () { return staffstage_1.staffstage_delete; } });
var user_1 = require("./user");
Object.defineProperty(exports, "user_list", { enumerable: true, get: function () { return user_1.user_list; } });
Object.defineProperty(exports, "user_listFields", { enumerable: true, get: function () { return user_1.user_listFields; } });
Object.defineProperty(exports, "user_create", { enumerable: true, get: function () { return user_1.user_create; } });
Object.defineProperty(exports, "user_createFields", { enumerable: true, get: function () { return user_1.user_createFields; } });
Object.defineProperty(exports, "user_read", { enumerable: true, get: function () { return user_1.user_read; } });
Object.defineProperty(exports, "user_update", { enumerable: true, get: function () { return user_1.user_update; } });
Object.defineProperty(exports, "user_updateFields", { enumerable: true, get: function () { return user_1.user_updateFields; } });
Object.defineProperty(exports, "user_partial_update", { enumerable: true, get: function () { return user_1.user_partial_update; } });
Object.defineProperty(exports, "user_partial_updateFields", { enumerable: true, get: function () { return user_1.user_partial_updateFields; } });
Object.defineProperty(exports, "user_delete", { enumerable: true, get: function () { return user_1.user_delete; } });
//# sourceMappingURL=index.js.map