# Generated by Django 4.0.5 on 2024-07-16 22:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('html', utils.db_fields.SanitizedHTMLField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionsRelatedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('html', utils.db_fields.SanitizedHTMLField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
