# Generated by Django 4.0.5 on 2024-07-10 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='questionsrelatedlink',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='questionsrelatedlink',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='answers',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100),
        ),
    ]
