# Generated by Django 4.0.5 on 2022-08-25 18:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('html', utils.db_fields.SanitizedHTMLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], max_length=1000)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('html', utils.db_fields.SanitizedHTMLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], max_length=1000)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newsletter')),
            ],
        ),
    ]
