# Generated by Django 4.0.5 on 2022-09-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_relatedlink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelatedLink',
            new_name='NewsRelatedLink',
        ),
    ]
