# Generated by Django 4.0.5 on 2022-09-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsletter_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='imageUrl',
            field=models.ImageField(null=True, upload_to='blah'),
        ),
    ]
