# Generated by Django 3.2.4 on 2021-12-11 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('pathUrl', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('passcode', models.CharField(max_length=1024)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('permission', models.CharField(choices=[('R', 'r'), ('W', 'W'), ('RW', 'rw'), ('RWD', 'rwd')], default='r', max_length=3)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity_api.app')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity_api.user')),
            ],
        ),
    ]
