# Generated by Django 4.0.5 on 2024-07-10 21:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('identity_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passcode',
        ),
        migrations.AddField(
            model_name='app',
            name='app_name',
            field=models.CharField(default='default_app_name', max_length=30),
        ),
        migrations.AddField(
            model_name='app',
            name='created_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='app',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='app',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='role',
            name='created_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='created_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity_api.user')),
            ],
        ),
    ]
