# Generated by Django 3.2.4 on 2021-11-13 11:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='r', max_length=3)),
                ('status', models.CharField(choices=[('1', 'activated'), ('2', 'deactivated'), ('3', 'pending'), ('4', 'confirmed'), ('5', 'archived')], default='r', max_length=3)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('shape', models.CharField(choices=[('1', 'Circle'), ('2', 'Square'), ('3', 'rectangle'), ('4', 'Triangle')], default='r', max_length=3)),
                ('status', models.CharField(choices=[('1', 'activated'), ('2', 'deactivated'), ('3', 'pending'), ('4', 'confirmed'), ('5', 'archived')], default='r', max_length=3)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('1', 'activated'), ('2', 'deactivated'), ('3', 'pending'), ('4', 'confirmed'), ('5', 'archived')], default='r', max_length=3)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('parentId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff_api.expertise')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('shape', models.CharField(choices=[('1', 'Circle'), ('2', 'Square'), ('3', 'rectangle'), ('4', 'Triangle')], default='r', max_length=3)),
                ('status', models.CharField(choices=[('1', 'activated'), ('2', 'deactivated'), ('3', 'pending'), ('4', 'confirmed'), ('5', 'archived')], default='r', max_length=3)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('nationalId', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('1', 'activated'), ('2', 'deactivated'), ('3', 'pending'), ('4', 'confirmed'), ('5', 'archived')], default='r', max_length=3)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PersonStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('step', models.CharField(choices=[('1', 'communication'), ('2', 'answers'), ('3', 'pending'), ('4', 'interview'), ('5', 'contract'), ('6', 'rejection'), ('7', 'refusal'), ('8', 'recommendation'), ('9', 'questions'), ('10', 'invitations')], default='r', max_length=3)),
                ('x', models.FloatField()),
                ('status', models.CharField(choices=[('1', 'activated'), ('2', 'deactivated'), ('3', 'pending'), ('4', 'confirmed'), ('5', 'archived')], default='r', max_length=3)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StaffStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('step', models.CharField(choices=[('1', 'communication'), ('2', 'answers'), ('3', 'meeting'), ('4', 'surveys'), ('5', 'administrative'), ('6', 'complains'), ('7', 'problems'), ('8', 'feedBack'), ('9', 'requirements'), ('10', 'legal'), ('11', 'questions'), ('12', 'gifts'), ('12', 'invitations')], default='r', max_length=3)),
                ('x', models.FloatField()),
                ('status', models.CharField(choices=[('1', 'activated'), ('2', 'deactivated'), ('3', 'pending'), ('4', 'confirmed'), ('5', 'archived')], default='r', max_length=3)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='staff_api.person')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('level', models.IntegerField()),
                ('bossId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff_api.staff')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.condition')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.department')),
            ],
            bases=('staff_api.person',),
        ),
        migrations.CreateModel(
            name='StaffLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('1', 'activated'), ('2', 'deactivated'), ('3', 'pending'), ('4', 'confirmed'), ('5', 'archived')], default='r', max_length=3)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.person')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.personstage')),
            ],
        ),
        migrations.CreateModel(
            name='PersonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('1', 'activated'), ('2', 'deactivated'), ('3', 'pending'), ('4', 'confirmed'), ('5', 'archived')], default='r', max_length=3)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.person')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.personstage')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertiseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('1', 'activated'), ('2', 'deactivated'), ('3', 'pending'), ('4', 'confirmed'), ('5', 'archived')], default='r', max_length=3)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.expertise')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.person')),
            ],
        ),
        migrations.CreateModel(
            name='StaffFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'activated'), ('2', 'deactivated'), ('3', 'pending'), ('4', 'confirmed'), ('5', 'archived')], default='r', max_length=3)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.function')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('1', 'activated'), ('2', 'deactivated'), ('3', 'pending'), ('4', 'confirmed'), ('5', 'archived')], default='r', max_length=3)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('1', 'activated'), ('2', 'deactivated'), ('3', 'pending'), ('4', 'confirmed'), ('5', 'archived')], default='r', max_length=3)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('1', 'activated'), ('2', 'deactivated'), ('3', 'pending'), ('4', 'confirmed'), ('5', 'archived')], default='r', max_length=3)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.staff')),
            ],
        ),
    ]
