# Generated by Django 4.0.5 on 2024-07-16 22:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('small', 'small'), ('mild', 'mild'), ('sever', 'sever')], max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('shape', models.CharField(choices=[('circle', 'circle'), ('square', 'square'), ('rectangle', 'rectangle'), ('triangle', 'triangle')], max_length=1000)),
                ('parentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_api.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('shape', models.CharField(choices=[('circle', 'circle'), ('square', 'square'), ('rectangle', 'rectangle'), ('triangle', 'triangle')], max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('level', models.IntegerField()),
                ('bossId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_api.staff')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.condition')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.department')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('step', models.CharField(choices=[('communication', 'communication'), ('answers', 'answers'), ('meeting', 'meeting'), ('surveys', 'surveys'), ('administrative', 'administrative'), ('complains', 'complains'), ('problems', 'problems'), ('feedBack', 'feedBack'), ('requirements', 'requirements'), ('legal', 'legal'), ('questions', 'questions'), ('gifts', 'gifts'), ('invitations', 'invitations')], max_length=1000)),
                ('x', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.personstage')),
                ('with_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.function')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
