# Generated by Django 3.2.4 on 2021-12-11 13:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='r', max_length=300)),
                ('status', models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], default='r', max_length=300)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('shape', models.CharField(choices=[('circle', '1'), ('square', '2'), ('rectangle', '3'), ('triangle', '4')], default='r', max_length=300)),
                ('status', models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], default='r', max_length=300)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], default='r', max_length=300)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('parentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='staff_api.expertise')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('shape', models.CharField(choices=[('circle', '1'), ('square', '2'), ('rectangle', '3'), ('triangle', '4')], default='r', max_length=300)),
                ('status', models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], default='r', max_length=300)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('nationalId', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], default='r', max_length=300)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PersonStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('step', models.CharField(choices=[('communication', '1'), ('answers', '2'), ('pending', '3'), ('interview', '4'), ('contract', '5'), ('rejection', '6'), ('refusal', '7'), ('recommendation', '8'), ('questions', '9'), ('invitations', '10')], default='r', max_length=300)),
                ('x', models.FloatField()),
                ('status', models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], default='r', max_length=300)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('level', models.IntegerField()),
                ('bossId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='staff_api.staff')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.condition')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.department')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.person')),
            ],
        ),
        migrations.CreateModel(
            name='StaffStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('step', models.CharField(choices=[('communication', '1'), ('answers', '2'), ('meeting', '3'), ('surveys', '4'), ('administrative', '5'), ('complains', '6'), ('problems', '7'), ('feedBack', '8'), ('requirements', '9'), ('legal', '10'), ('questions', '11'), ('gifts', '12'), ('invitations', '13')], default='r', max_length=300)),
                ('x', models.FloatField()),
                ('status', models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], default='r', max_length=300)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StaffLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], default='r', max_length=300)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.personstage')),
                ('with_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_api.person')),
            ],
        ),
        migrations.CreateModel(
            name='StaffFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], default='r', max_length=300)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.function')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], default='r', max_length=300)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.staff')),
            ],
        ),
        migrations.CreateModel(
            name='PersonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], default='r', max_length=300)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.person')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.personstage')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertiseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], default='r', max_length=300)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.expertise')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.person')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], default='r', max_length=300)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], default='r', max_length=300)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_api.staff')),
            ],
        ),
    ]
