# Generated by Django 4.0.5 on 2022-07-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_api', '0004_department_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='status',
            field=models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='comments',
            name='status',
            field=models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='condition',
            name='severity',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='condition',
            name='status',
            field=models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='department',
            name='shape',
            field=models.CharField(choices=[('circle', '1'), ('square', '2'), ('rectangle', '3'), ('triangle', '4')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='status',
            field=models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='expertiseprofile',
            name='status',
            field=models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='function',
            name='shape',
            field=models.CharField(choices=[('circle', '1'), ('square', '2'), ('rectangle', '3'), ('triangle', '4')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='function',
            name='status',
            field=models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='personlog',
            name='status',
            field=models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='personstage',
            name='status',
            field=models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='personstage',
            name='step',
            field=models.CharField(choices=[('communication', '1'), ('answers', '2'), ('pending', '3'), ('interview', '4'), ('contract', '5'), ('rejection', '6'), ('refusal', '7'), ('recommendation', '8'), ('questions', '9'), ('invitations', '10')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='stafffunctions',
            name='status',
            field=models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='stafflog',
            name='status',
            field=models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='staffstage',
            name='status',
            field=models.CharField(choices=[('activated', '1'), ('deactivated', '2'), ('pending', '3'), ('confirmed', '4'), ('archived', '5')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='staffstage',
            name='step',
            field=models.CharField(choices=[('communication', '1'), ('answers', '2'), ('meeting', '3'), ('surveys', '4'), ('administrative', '5'), ('complains', '6'), ('problems', '7'), ('feedBack', '8'), ('requirements', '9'), ('legal', '10'), ('questions', '11'), ('gifts', '12'), ('invitations', '13')], max_length=1000),
        ),
    ]
