# Generated by Django 4.0.5 on 2022-08-25 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('staff_api', '0005_alter_address_status_alter_comments_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertise',
            name='parentId',
        ),
        migrations.RemoveField(
            model_name='expertiseprofile',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='expertiseprofile',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personlog',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personlog',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='staff',
        ),
        migrations.AlterField(
            model_name='comments',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='condition',
            name='severity',
            field=models.CharField(choices=[('small', 'small'), ('mild', 'mild'), ('sever', 'sever')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='condition',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='department',
            name='shape',
            field=models.CharField(choices=[('circle', 'circle'), ('square', 'square'), ('rectangle', 'rectangle'), ('triangle', 'triangle')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='function',
            name='shape',
            field=models.CharField(choices=[('circle', 'circle'), ('square', 'square'), ('rectangle', 'rectangle'), ('triangle', 'triangle')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='function',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='staff',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person'),
        ),
        migrations.AlterField(
            model_name='stafffunctions',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='stafflog',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.personstage'),
        ),
        migrations.AlterField(
            model_name='stafflog',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='stafflog',
            name='with_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.person'),
        ),
        migrations.AlterField(
            model_name='staffstage',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='staffstage',
            name='step',
            field=models.CharField(choices=[('communication', 'communication'), ('answers', 'answers'), ('meeting', 'meeting'), ('surveys', 'surveys'), ('administrative', 'administrative'), ('complains', 'complains'), ('problems', 'problems'), ('feedBack', 'feedBack'), ('requirements', 'requirements'), ('legal', 'legal'), ('questions', 'questions'), ('gifts', 'gifts'), ('invitations', 'invitations')], max_length=1000),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Expertise',
        ),
        migrations.DeleteModel(
            name='ExpertiseProfile',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PersonLog',
        ),
        migrations.DeleteModel(
            name='PersonStage',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
