# Generated by Django 4.0.5 on 2022-09-03 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_api', '0007_rename_comments_staffcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='parentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_api.department'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='bossId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_api.staff'),
        ),
    ]
