# Generated by Django 4.0.5 on 2024-07-10 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff_api', '0008_alter_department_parentid_alter_staff_bossid'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='function',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staff',
            name='created_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staffcomment',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stafffunctions',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stafflog',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staffstage',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='condition',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='function',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffcomment',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='stafffunctions',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='stafflog',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffstage',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('archived', 'archived')], default='pending', max_length=100),
        ),
    ]
